== Chapter 1.

[.chapter-synopsis]
* Her birth
* Early preservation and visitation
* Removal to Worcester
* Visit of Elizabeth Ashbridge and Sarah Worral
* Removed to the Isle of Man
* Her exercises there
* Returns to England
* Decease of her father
* Settles a while at Lancaster
* First appears in the ministry at Worcester
* Welch Yearly Meeting
* Settles in Wiltshire.

Sarah Stephenson,
some of the occurrences of whose life are related in the following pages,
was born at Whitehaven, in Cumberland, in the year 1738.
Her parents were Daniel and Sarah Stephenson, of whom she was the elder daughter.
Her mother was the daughter of Joseph Storrs, of Chesterfield, Derbyshire.
Of events which were her lot in childhood and youth, of her conflicts and consolations,
and her preservation from harm and evil, at those stages of life,
the subsequent account is nearly in her own words.

"`The remembrance of the great love and tender care of the Shepherd of Israel,
who sleepeth not by day nor slumbereth by night, from my infant days to the present time,
is cause of deep admiration, reverence, and abasement of soul.

"`When I was about six years of age, I had a narrow escape of being burned to death,
by falling on the fire when no one else was in the room.
This preservation, as also another,
by which my soul was signally rescued from the jaws of the devourer, in very early life,
I attribute only to Him, who hath, in the course of my pilgrimage,
succoured me in many deep and proving seasons;
and hath borne up my head above the mighty waters,
even when the waves have risen so high as to appear likely to overwhelm me.
O, my soul, mayest thou never be unmindful of the Lord`'s unutterable goodness,
but walk humbly and reverently before him,
who is abundant in mercy and great lovingkindness!

"`It may not be improper to mention,
that my father carried on a very considerable business in the mercantile way,
and had gained much property.
This, and living in what is called a genteel style,
and being introduced into company of high rank when very young,
so pleased my natural disposition, that I began to take steps in the paths of vanity.
But, whilst I was thus pursuing with eagerness,
what are called by some innocent diversions, the good Shepherd,
who seeketh after those that are gone astray, looked down upon me in love,
and so enamoured my soul with his beauty, that I loved to be alone with him.
O, how sweet was his presence!
But this lasted not long;
for the enemy painted the glory of this delusive world in such pleasing colours,
that I forsook the Prince of peace, and proceeded still further in the paths of vanity.

"`My father, as I have mentioned, was trading largely;
and he so extended his business that he could not himself have the oversight of it.
This was attended with losses and many disappointments;
and at length occasioned the separation of the family.
My uncle, William Storrs, of Chesterfield, took me to Worcester, to my mother`'s sister,
and there, being afresh favoured with a precious visitation,
I was mercifully prevailed on to close in with it.

"`After I had been in that city a few months, those worthy servants of the Lord,
Elizabeth Ashbridge and Sarah Worral, from America, came to my uncle`'s house, and,
I think, stayed some days.
One evening, during this time, Elizabeth, in a very weighty manner,
addressed me in the language of unspeakable love; remarking also,
'`What a pity that child should have a ribbon on her head.`' Her words were piercing,
and deeply affected my mind.
I do not know that I closed my eyes to sleep that night; and in the morning,
not daring to put on my ribbon, I came down without it.
Yet I had many fears, expecting to be censured by one of the family,
as having left it off to get the favour of the Friends, and from this unjust ground,
the enemy caused many seasons of sorrow.
This was coming a little to the gate of stripping, which work went gradually forward;
but great were my trials, both from within and without.
Indeed my conflicts were so great, that I might say, '`I ate my bread with mourning,
and mingled my drink with tears;`'--but then, O,
what precious meetings I had at times! my spirit was so broken,
that I could scarcely contain myself.
Here were also divers weighty valuable friends, whose sympathy with me was great,
and was a comfort to me.
It likewise pleased Divine Wisdom, while I remained at Worcester,
to permit me to be attacked with a slow fever,
which reduced me to such a state of weakness,
that it seemed not unlikely I might sink under it.
But that did not prove to be the design of unerring Wisdom;
but rather to make it preparatory to fresh exercise and trial of faith.
In this time of great weakness and reduction of will, my mind was sweetly supported, and,
at seasons, favoured with the overshadowing of Divine love,
under which my soul humbly and thankfully rejoiced.

"`When I was a little recovered from this illness,
a trial of a close nature was my portion.
I received a letter from my father, who, in a pressing manner,
requested my going home to live with my dear parents,
whom I had not seen for seven years.
In my absence, they had removed, together with my sister and my youngest brother,
to Douglas, in the Isle of Man, at which place were no others of our Society,
and the inhabitants were much strangers to it.
Great were the struggles and fears that attended my poor mind,
and prayer was begotten that by obeying my natural parent,
I might not offend my heavenly Father, who had so richly visited my soul.
But the Lord was pleased so to open my way, that it appeared right to go; yet O,
the fear that covered my mind, lest I should bring a reproach on the Truth.
My humble cries were put up unto him for preservation,
and he was mercifully pleased to hear, and measurably to answer, my petitions.
In this humbled state I left Worcester,
being favoured with the love and sympathy of many worthy Friends.
Catherine Payton, who then lived at Dudley, was one:
she wrote a sweet consolatory letter to a Friend, which was given to me to peruse,
in which she said, '`If she must go, let her take some Friends`' books with her;
and may she be preserved, like Lot in Sodom, a preacher of righteousness.`'

"`I went on horseback to Liverpool, where I was kindly received by an agent of my father,
to whom he had written to procure me a passage; and his wife,
being a tender-spirited religious woman, was like a mother to me.
She was not of our Society.
I stayed at Liverpool about two weeks before I could get a conveyance,
in which time many Friends took kind notice of me,
and I contracted a near affection for some of them.
I believe their minds were drawn in true love to me; and, being grounded, I trust,
on that foundation that is not to be shaken, it has stood many years, and, I hope,
will remain.
But this favour was the great Master`'s kindness, for which,
with multiplied mercies vouchsafed to me, a poor worm,
may my soul reverently and devotedly follow him.

"`I went on board one of the packets,
with my mind humbly turned to the great Preserver of men, whose ways are in the deep,
and beheld in the mighty waters; but, though it was quiet,
I was soon sick and went to bed, the sea being rough and the vessel leaky;
and in the night there was such a storm, that it seemed likely we should be lost.
The poor seamen were in great confusion, and I in the cabin alone,
not expecting to see the light of another day.
But O, the unutterable love of Christ, who,
in this time of great danger was pleased to be near, and kept my mind in a sweet calm,
so that had he been pleased to permit the sea to be my grave that night,
I believe my spirit would have been mercifully received into everlasting rest.
O my soul, mayest thou never be unmindful of his manifold mercies and deliverances,
and walk in fear and humble obedience all the remainder of thy days,
that when the close approaches, thou mayest be ready to enter,
with the glorious Bridegroom, into the marriage chamber.

"`The storm abating, we were favoured to arrive next day at our intended port;
where I was received by my near relations with affection;
but my new situation opened new trials.
Here I was as one alone, and viewed myself like a sparrow upon the house-top,
a pelican in the wilderness, or an owl in the desert.
O, the many exercises I passed through! the Lord only knows them;
but my prayers being strong to him for preservation,
he was pleased to hear my cry and at seasons to feed and comfort my needy soul.
I found my safety to depend on keeping much inward, and not mixing with the people;
though some of the genteeler sort showed me marks of respect,
and invited me to their houses; but I declined going,
for their company was burdensome to me.
I used to walk in the fields alone, and can feelingly sympathise with honest minds,
who are remotely situated and placed as alone.
I wish to encourage them singly and steadily to lean upon and trust in the God of Israel,
who will not leave nor forsake his poor wrestling seed,
but will work deliverance for them in the way that is best.

"`Hearing that two women were come to the island, who were said to be Quakers,
I went to see them, in hopes of having in them companions in the right way; but,
to my painful disappointment, I found them playing at cards: so I visited them no more.

"`Though many were the trials,
yet I have cause to believe that my going to the island was right.
One of these trials, which came very near to me, was this.
My dear father, whom I tenderly loved, and who loved me much,
requested me to do something which I felt was opposite to the cross of Christ,
and there were present at the time one or two of those called gentlemen; but,
not daring to offend the precious Witness, I declined compliance,
though it was a great trial to offend my dear father.
None but those alike circumstanced can tell how great is the trial in such a case.
My dear parent was so displeased that I should disobey him,
that it was a considerable time before he was reconciled.
I endeavoured by watchful attention and obedience,
to evince from what motive the refusal arose;
and after a time his love not only returned, but I think was greater than before:
what abundant cause there is to trust in the Lord Jehovah, who has a right to be loved,
honoured and obeyed above all.

"`When I had been on the island about a year and a half,
my dear mother one day asked me if I would like to
go and see my friends in England that summer.
I then made but little answer to her kind offer; but,
being deeply humbled and very desirous to be rightly directed,
a great fear came over my mind, lest, by being gratified in what was so very desirable,
the company of valuable friends, I should be going away from that suffering,
which possibly, was my proper allotment; and so,
instead of being strengthened and comforted, should suffer loss.
In this deeply tried state I remained several days;
for thus in wisdom it pleased my heavenly Father to prove me,
whether I would move without his counsel or not.
I supplicated him in prostration of mind, and sometimes of my body also;
and in his own time, he was pleased to break in upon my soul, and utter the language,
'`Go, and I will be with thee.`' Then, O,
the reverent thanksgiving that flowed from my poor suppliant spirit!
It may be best conceived by those who have trodden a like path.
I believed with my whole heart,
and can say that all the promises of adorable Goodness are indeed yea and amen forever!

"`After being thus favoured, I informed my dear parents,
that as they were so kind as to propose my having the pleasure of visiting my friends,
I should be glad to accept of it.
My dear father then went with me to a vessel which was ready to sail for Liverpool,
and putting me under the care of a captain of another ship who was a passenger,
we parted, and I never saw my dear parent more, for he died before I returned.
Had I gone without feeling the approbation of the Redeemer of mankind,
I think the trial would have been much greater than it was,
though it was indeed a close one.

"`I arrived at Liverpool, and was kindly received by my friends,
and thence went to the Northern Yearly Meeting held that year, (namely, 1762) at Bolton,
in company with William Rathbone and his sister.

"`There was Catherine Payton, also Samuel Fothergill,
and others of the Lord`'s faithful servants, many of whom were affectionately kind to me.
From Bolton I went to Chesterfield and to Worcester, and into Wiltshire.
After having visited my relations in these places, I returned into the North,
to Lancaster, where I had a letter informing me that my dear father was ill,
and I set off in hopes of seeing him,
but he was dead and buried before I could reach home: which was not a small trial;
but in this I have had to trace deep and hidden wisdom.

"`To return to my first going home; I had cause to believe it was in right ordering,
and that it was of some use to my dear sister, who was quite in the gaiety of the world,
though there was no evident effect till after my father`'s decease.
The winter coming on, we concluded to remain on the island until spring,
and then we all removed to Liverpool.
My youngest brother, who was, I think, about ten or eleven years old, was sent to school;
my sister, after a few months, went to Birmingham; and my mother and I were left.
After awhile, my mother inclined to give up housekeeping,
and to have an apartment in the house of a valuable Friend.
When she was settled there, much to her own satisfaction, I went to Lancaster,
to my cousin William Dillworth,
who had written to request that I would come to be as one of his own children.
Indeed he was a most tender father, and his daughters as my own sisters.
The families also of my cousins Thomas Dillworth and John Bradford,
were such families of love, that they also seemed like so many fathers and mothers to me.

"`I may now mention that while I was at Liverpool
I had a prospect of the awful service of the ministry;
and after being awhile at Lancaster, my cousin John Bradford had a sense of it,
and mentioned it in a private opportunity.
But, I saw myself such a poor creature, and the work so awfully great,
that I did not give up to it during the two years I was there,
nor until sore trials made me willing;
though I was once so near obeying the heavenly call,
that my hand was put on the seat before me, to help myself upon my feet.

But O, the fears which kept me back, and the bitter cups which they occasioned!
I believe they would never have been my portion,
had I simply followed Him who had been my support in many seasons of deep distress,
and my sweet comforter in the day of trouble.

"`During this exercise, a further trial attended me.
I received information from Liverpool, that my dear mother was so very poorly,
that it was needful for me to come speedily to her.
I hastened thither accordingly,
though it was pinching to me to leave my dear relations at Lancaster,
and finding her very unwell, I stayed with her a considerable time;
and as her complaints rather increased,
my mind was exercised beyond what I can well express.
About this time we received a letter from our relations in Wiltshire,
inviting us to go there, hoping a journey might be of service.
As my mother was willing to try, we set out and got to Worcester,
where we made a little stay.
Here my gracious Lord and law-giver was pleased to lay a concern weightily upon me,
to enter on that great work of the ministry; and in one of the meetings,
in which were two valuable ministers, who had something very weighty to drop,
and who had a sense of my state, the power of Truth was such,
that I dared no longer to delay; and in awful fear stood up,
having these expressions given to me, '`Cry aloud, spare not.
Lift up thy voice like a trumpet, and show my people their transgressions,
and the house of Jacob their sins.`"
I was then sweetly comforted,
and being favoured with the unity of the Lord`'s faithful servants,
it was very strengthening to my doubting mind.

"`After staying a week or two sit Worcester, my dear mother gradually getting better,
we set out for Wilts, and remaining a few weeks there,
I left my mother finely recovered at my uncle John Fry`'s,
and went to see my relations in Bristol.
Here, as well as when in Wiltshire,
I was at times engaged to appear in a short testimony,
which seemed acceptable to Friends, and the solid part took a kind notice of me.
While at Bristol, my mind was engaged under a sense of duty,
to attend the Welch Yearly Meeting, to be held at Builth, in Brecknockshire,
the 5th of the fifth month, 1767.
Being young, and knowing of no Friends going thither, I was much sunk;
but on making my state of mind known to one or two Friends, my way, as to the outward,
was made easy.
Catherine Payton, Rachel Wilson, and divers others who were there,
were as nursing mothers to me; but what was above all,
was the presence of my dear Redeemer,
enabling me to do what little service he was pleased to require: with which,
I had reason to believe Friends had good unity.

This was cause of humble thankfulness to the God of my life,
who continues to regard the dust of Zion, and to satisfy her poor with bread.
O my soul, mayst thou ever fear,
and walk reverently before Him who is the dread of nations!

"`I returned pretty directly from this meeting to Bristol,
with the reward of sweet peace for this little service.
After staying there some months, I had a letter from my uncle John Fry,
requesting I would come to Sutton, where he resided, which 1 did.`"
