== Chapter V.

Visits families at Worcester,
and in her own Monthly Meeting--Visits Ireland with Hannah
Bevington--Decease of Isaac Gray--Meets with Thomas Cash,
John Pemberton and Thomas Ross--Various family visits, particularly at Cork.

The occurrences of the years 1782 and 1783, of which any account is preserved, are few.
Early in the former year, our friend visited the families of Friends in Worcester,
and was afterwards engaged in a like service to those of her own Monthly Meeting.
In the latter she had Mary Powel for a companion: who was also with her in 1783,
on the same service, in some other parts of Wiltshire, particularly at Salisbury.
The same year,
she paid a similar visit to the Friends of some meetings in Somersetshire and Gloucestershire.
In these visits she had the company of her sister, Hannah Stephenson.

Hitherto, the travels of Sarah Stephenson, though extensive,
had been confined to Great Britain; unless we except her residence, while young,
in the Isle of Man,
which was not on an errand similar to those which occupied her riper years.
But in the spring of 1784, she crossed the sea,
and entered on a visit to Friends in Ireland.
Of this visit she has left an account,
which is given to the reader in the following pages, nearly in her own words.

"`On the 9th of the second month, 1784, I laid before Friends,
at our Monthly Meeting at Melksham, a concern which I felt for going to Ireland;
which being united with,
a certificate was prepared and signed at the following Monthly Meeting, held at Devizes,
and also at the Quarterly Meeting the 22nd of the third month.

"`I left Melksham the 14th of the fourth month, and went by way of Hampton, Tewksbury,
Worcester and Shrewsbury, having favoured,
tendering opportunities at divers of these places,
and reached Holyhead the 23rd. I felt many discouragements and buffetings at times,
but my gracious Preserver rebuked the destroyer, or I fear I should have been overset.
The 24th, the wind being contrary, no packets sailed today.
I have remembered the great attainment of the apostle,
respecting his being in all states content.
May my mind be centered in the Divine will, and in that quietly rest.

"`My companion, Hannah Bevington,
feeling a desire to have an opportunity with the inhabitants,
and knowing of no convenient place in the town, we walked to the steeple-house yard;
and when the people came out, we stood by the market-cross,
a spot that commanded them in general as they passed,
and I think the power of Truth was sensibly felt to be extended towards them.
As soon as we felt ourselves at liberty, we withdrew, and returned to our inn.
The wind soon became favourable, and we sailed about three o`'clock in the afternoon,
and had a fine passage, but I was very sick, yet favoured with quiet resignation.

"`The tide did not serve for the packet to go over the bar;
so we got into a wherry to go up the river, about five miles.
It rained very hard, and I was very wet, and took a severe cold,
which confined me several days.
We arrived at Dublin the 26th, after a passage of about twenty-three hours.
I was confined by indisposition until the 2nd of the fifth month,
at the house of my kind friend Joseph Williams,
and then went to meeting at Sycamore-alley,
and felt strength to deliver what seemed my duty.
I think it was a favoured meeting.
The Half-year`'s Meeting began on the 3rd, and I attended the different sittings,
which concluded on the 6th, and on the 7th, we set off for the north,
and arrived on the 8th at Rathfriland, fifty-seven Irish miles.

"`On the 9th, was at meeting in the morning,
in which the states of some were opened and spoken to:
and another meeting in the afternoon, a season in which Truth spread,
for which my soul doth bless His holy name who is worthy forever.
The 11th we had a wading meeting at Moyallen,
but were enabled to leave with the people what seemed our duty.

"`On the 12th I was so unwell,
that my companion went without me to a meeting appointed at Lurgan.
I believe my indisposition was permitted in best wisdom, for I was not clear of Moyallen;
and the 13th being the weekday meeting there, we attended it.
It was large and a favoured time, in which I was set at liberty and felt very peaceful.
We had also other opportunities more select, and one at our lodgings,
in which condescending ancient goodness covered our spirits,
and we were favoured with the droppings of celestial rain.
The 16th we proceeded to Lurgan, and had a meeting there, and so on to Ballyhagen,
Lisburne, and other places in that quarter.
On the 20th, at a meeting at Lisburne, my mind was led into an earnest travail,
and it was mercifully regarded by our gracious Master, who moved my spirit in his love,
to stand up with the language of Christ to his immediate followers,
'`Children have ye any meat?`' Truth spread, and led to deliver close things,
but under the tenders of softening love, which seemed to melt many minds,
and much contrited my spirit before Him who condescends
to make use of mean and contemptible instruments.

"`We went to Hillsborough, Antrim and Ballymena, and had a meeting in each place,
besides other opportunities, in which best help was near,
enabling us to discharge our duty.
As we were on the way to Ballinacree, we were met by a Friend,
who came to inform us of the death of our dear friend Isaac Gray, from England,
whom we had met at Lisburne on the 18th. The sudden removal of this our dear Friend,
greatly affected my companion and myself.
He was to be buried the next day at Charlemount.
The morning of the day on which he died, he complained of feeling unwell,
with pain in his breast or stomach, for which something being given him,
he desired his companion and Friends to go to meeting.
The Friend who stayed to wait on him, observing him lie still, supposed he was asleep,
and his companion, for fear of waking him,
did not go immediately into the room after meeting,
but took a little walk into the fields.
On his return, he was met by a Friend who told him that dear Isaac was dead,
and it was supposed, had been so for some time.

"`On the 27th, we rode to Coleraine, and had a meeting there;
and on the 28th to Toberhead, where was a large meeting, mostly of other societies.
It was an open time, and I hope satisfactory.
We were at our valuable friend Gervas Johnson`'s,
where Isaac Gray had died the second-day before.
The being there so soon after his death afresh affected our minds; may we learn,
under proving dispensations to say.
Not our wills, but thine, O Lord, be done.
We afterwards went to Dungannon, and from thence to Ballyhagen.
Thomas Cash of Morley, in Cheshire, who had been Isaac Gray`'s companion,
was with us there at meeting, a season owned by the Master.

"`The 1st of the sixth month, my mind was very low.
May I profit by every dispensation permitted to attend;
for indeed varied and deep are the provings of the
poor servants in this day of deep degeneracy.
After meetings in some other places, we attended the province meeting held at Ballyhagen.
My mind at this time was much impressed with a sense of its being required
of us to visit the families of Friends belonging to Grange meeting;
but I was desirous to weigh it still further.
So we went to some other meetings, but I could not be easy to proceed far, any other way;
therefore returned to Grange.
We attended the week-day meeting on the 9th,
at the close of which our concern was mentioned,
and way was made for accomplishing the visit.

"`We began the arduous service on the 10th,
and I was favoured with an evidence of being in the way of my duty.
O, holy Father, keep my soul stayed on thee,
and permit nothing to draw my attention from thee,
but be pleased to enable me to obey every manifestation of duty.
And O, my soul, mayest thou be instructed,
and whilst endeavouring to dress the vineyards of others, not to leave thy own undressed.
The 13th, sweetly refreshed in solemn silence.
The 14th, today have had several seasons of close labour and deep exercise,
under which my spirit mourns for the whole, unsafe state of some,
and the insensibility of others,
desiring that all self-righteousness may be stripped off,
and their minds brought into that state of self-abasement,
with which the Most High is well pleased: that so sweet life in him may be experienced.
The 20th, first-day, a very solemn meeting held in silence.
My mind was opened to view the beauty, necessity,
and excellency of knowing every thought brought into the obedience of Christ.

"`At Dungannon we visited families, and left it with humble thankfulness,
believing we had been enabled to get safely through that arduous service,
under which we had many close baptisms,
but were favoured to feel peace as the reward of obedience in discharging
that duty which we believed our gracious Leader required of us.
We then went to Oldcastle, Moat and Ballymurry.

"`The 4th of the seventh month, and the first-day of the week, at meeting this morning,
my spirit centered in awful prostration and travail for the people,
and I felt the gentle descendings of best love,
accompanied with a draft to stand upon my feet: and as Truth opened my way, I spoke,
and matter was given,
under the guidance of that Spirit which not only leads safely forth,
but also back to the tent, with the reward of peace.
O, my God, be pleased to continue the guidance of thy holy Spirit,
and keep me as in the hollow of thy hand,
that I may be preserved in the way of thy requirings.
The 6th, I was at a meeting at Moat, where we had the company of our dear friends,
John Pemberton, from Philadelphia, and Thomas Cash.
It was a season owned by our gracious Leader.
The 8th, at a meeting at Rathangan.
Part of the time there was a painful sensation occasioned
by the desire of some after words.
It tended to close our way, but after awhile I felt the moving of Truth to public labour,
and in simplicity stood up.
After speaking a few words, the power arose beyond what I have often known, through me,
a poor creature.
The 9th, was at meeting at Timahoe, and visited some families, and on the 11th,
attended a meeting at Edenderry, a season of deep travail; but life arose,
and for a time dispelled the clouds, and many were much broken.
Close things were spoken under the covering of Gospel love,
and I hope it was a good meeting.
From thence we went to Ballitore.

"`As I rode along, my mind was greatly stripped, and very poor;
and feeling the low state of things, was much dejected by it.
But O, my gracious Father, be pleased not to leave me,
nor permit me to grow weary of suffering;
but enable me to follow thee in the way of regeneration.
We lodged at Richard Shackleton`'s,
and my mind became impressed with its being our duty to visit the families;
which we were enabled to enter upon under an awful
sweet covering of our heavenly Father`'s love,
and in an humbling sense of our own weakness.
We had some painful laborious sittings;
but there is a remnant who are sighing and mourning for the state of backsliders,
and are also contending for the faith.
With these our spirits were refreshed.
We visited the meeting at Castledermot, and attended a burial at Ballitore;
also were at another meeting there.
I had to caution against being anxious after words, believing that,
had it not been the case at that time,
we should have been much more favoured with the company of Christ.

"`From Ballitore, we went to two or three other meetings, in one of which,
I had very painful feelings, the pure Seed being greatly oppressed.
O, how did my spirit mourn, adopting the language of that deeply tried prophet,
when he said, '`O, that my head were waters, and mine eyes a fountain of tears,
that I might weep day and night for the slain of the daughter of
my people.`' We were enabled to deliver what appeared our duty;
and in the afternoon, a little consolation was given to the few mourners in Zion.

"`In the next meeting we attended, my spirit was led into a deep travail,
and feeling it my place to stand up,
I was helped to speak to divers states under the flowing of best love;
my companion also had a favoured time,
and my spirit was engaged to supplicate the Almighty vocally;
which service is to me very weighty;
but I hope we may humbly acknowledge that our gracious
Leader was with us to the contriting of our minds.

"`At a meeting at +++_______+++, I felt the motion of Truth to stand up, though in weakness;
but Truth arose, and matter opened far beyond my expectation;
so that many minds were much tendered,
and my spirit humbled before Him who condescends
to make use of mean and contemptible instruments.
In the evening was at a meeting at +++_______+++. The forepart was low, but life arose,
and in some degree of best authority, the backsliders were warned, and in a manner that,
I believe, reached the witness.
May they not sink into a state of sorrowful self-gratification,
and have to call to the hills and mountains for shelter,
when the dread hand-writing may be seen on the wall.
The few mourners and sorrowful spirits were sympathized with and encouraged,
the slothful were called to arouse from their false ease,
and I hope it was a favoured meeting.
The 23rd my way was closed up at Mountmelick meeting,
by feeling a strong desire in the people for words,
and at the close I felt it my place to tell them that I believed
they had prevented the handing forth of spiritual bread,
by not attending to the language that saluted my mind early in that meeting; which was,
study to be quiet, and mind thy own business: to which I had endeavoured to attend.

"`The 29th, we went to Moat, and the 30th,
entered on the weighty service of visiting families there.
Some seasons were much owned by our gracious Leader, tending to encourage us,
and to confirm the belief of being in the way of our dear Master`'s requirings.
From Moat we went to some adjacent meetings and back again,
and visited some families at Athlone and Ballymurry.
We sat with several persons who had been disunited for misconduct.
After one opportunity,
one of the family informed us how his mind had been
visited in a very extraordinary manner,
and he was thoughtful whether it might not be best to tell the people,
thinking it might be of service;
but it seemed clear to me that this was an artifice of the enemy,
in order to draw him from his own work, and proper business;
and I strongly advised him to keep in the stillness, and feel deeply for the pure life,
that therein he might grow.
He received the advice in love, in which we parted.

"`The province meeting began on the 14th, at Moat, in which my mind was much exercised,
and it was a favoured time;
but I was weightily impressed with a requiring to return to Oldcastle,
and visit the few families there,
of which I had informed my dear companion some days before.
Some Friends were going that way, with whom we concluded to go,
but my mind was dipped very low under discouragement.
A valuable Friend who was there, understanding the concern I was under,
came and saluted me with these words;
'`I am glad that thou art willing to do whatever thy Master biddeth
thee.`' He was a man of sound judgment and deep in spirit,
and there was such weight and sweetness accompanying the words,
that they entered my soul, and were as a cordial.

"`We set out on the 15th, and were that evening at an inn,
with several Friends in company.
While supper was preparing,
our spirits became deeply centered and baptised in sweet silence,
under such a covering of the Father`'s uniting love, as very much contrited us,
and made us near to each other in the covenant of love and life.
The next morning we went to Oldcastle,
and had cause to believe that our return was in the ordering of Divine wisdom,
whose right it is to dispose of his servants, as it pleaseth him.
We afterwards returned to Moat, and at a week-day meeting,
I took a solemn leave of Friends there,
reviving in their remembrance that they had been invited,
some of them in the most persuasive language, to quit the paths of error,
and to obey Christ; but observing that, if such would not be prevailed on,
their blood would be upon their own heads.
It was a tendering season to some minds present.

"`We sat a considerable time in silence, at Kilconnermore, on the 20th,
and in great poverty.
Yet it seemed my place to stand up,
though in so much weakness that I thought I had hardly strength sufficient to do so;
but I obeyed the secret motion of Truth;
and when on my feet had to speak on the advantage
of knowing Jerusalem to be a quiet habitation,
a place of succour in the day of storm, when we should be searched, as with candles:
and though pretty close things opened, yet it was under the power of love, so that,
if I felt aright.
Truth arose into a good degree of dominion, and great tenderness was in the meeting.
O, my soul, thou hadst indeed much cause to believe in the sufficiency of His power,
who is the resurrection and the life.
We went to see five children that were orphans.
They were so tendered in the opportunity we had with them,
that they could not forbear weeping aloud.
The dear children were recommended to read the Scriptures,
and the blessing attendant on obedience +++[+++to the Lord`'s will]
was set forth to them.
O, may the visitors and visited remember and profit by such condescending goodness,
such favour from adorable Mercy.
The 25th, I was at a meeting at Knock, where I stood up in much fear and awful dread,
under the feeling of different states, and of a spirit that, like Goliath,
defied the armies of Israel`'s God;
but gracious Goodness clothed me with strength to attack it, and by his power it seemed,
for the present, brought under, for an awful covering was over the meeting.

"`The 27th we went to Limerick.
The 29th being first-day, we sat two meetings there.
My spirit was sunk very low, and stripped;
but much exercised under an apprehension of its being required of me to visit the families.
I informed my companion how it was with me,
of which she had a sense from the dipped state of my mind.
The 31st being the day of the Monthly Meeting, we imparted the concern to Friends,
and as they united with it, we proceeded on the visit,
and by the next second-day accomplished it.
There were about twenty-four families.
My spirit was much exercised in this service; but renewed ability to labour was afforded,
and different states I hope were rightly opened.
On the seventh-day came Thomas Ross from America, and we had his company on first-day,
at the two meetings,
also at one in the evening at Thomas Mark`'s. He is a sweet-spirited man,
much devoted to his Master`'s service.

"`We left Limerick the 6th of the ninth month, in company with him,
and took one meeting in the way to Clonmel, in which my mind was bent, in near affection,
towards the dear youth.
At a meeting at Clonmel, dear Thomas Ross was much favoured in public.
My mouth was not opened, but I was led to visit many in silence;
and a humbling prospect was afresh opened, respecting visiting the families there,
of which I had a view when at home;
but as the time of the Quarterly Meeting at Waterford was nigh, we went thither;
where also were John Pemberton, Thomas Cash, and Thomas Ross.

"`Though the Lord at this time was pleased to employ me in public,
and also in more select companies, yet deep were the conflicts of my spirit,
both on the road to Waterford, and when there, until I gave up to mention a concern,
which I had felt when at my own home, to visit Friends in their families at that place.
Afterwards my spirit, though awfully bowed under it, was clothed with a sweet calm.

"`We left Waterford the 15th,
and had the company of our valuable Friends John Pemberton and Thomas Cash,
on the way to Clonmel.
The 16th, was a meeting, in which they both spoke, myself employed in profitable silence.
The 18th, we entered on the laborious service of visiting families at Clonmel.
In divers of the sittings I had cause humbly to believe it was a right engagement,
our dear Master being graciously near,
and opening different states in a remarkable manner.
May such seasons of condescending goodness remain to be cause of fresh humiliation,
and lead my soul to a firm trust in His holy name,
who has been pleased thus to employ me, not only in this place,
but in several others in this province of Munster,
which had been very closely fixed on my mind before I left home.
O, my soul,
mayst thou be more and more centered in humble devotedness to the requirings of thy God,
who is worthy forever, to be served, worshipped, and adored!

"`We have now gone through great part of the families, and have cause to say.
Hitherto the Lord hath helped us.
Indeed he has enabled me to deal plainly, and honestly to discharge my duty;
and I hope we have left an open door for such as may come after us.
We also visited the families at Garryrone, to our satisfaction,
and were at some other meetings; thence returned to Waterford,
and the 9th of the tenth month began the arduous service of visiting families there;
my soul being dipped as into the bottom of Jordan.
May all within me be so entirely submissive,
as that the Lord`'s voice may be deeply attended to, and wholly obeyed in simplicity;
that his blessed will may be done by me on earth, as it is done in heaven.

"`On first-day, the 10th, sat two meetings in humble, and I hope profitable silence:
after the second, paid two visits.
We pursued the engagement diligently, and were enabled,
I hope under a good degree of right authority,
even the covering of the wing of ancient Goodness, to speak to different states.
Some of the opportunities were memorable seasons,
to the comfort of both visited and visitors.
Tendering invitations were extended to some of the youth,
but close matter handed to others.
O, may the slothful be awakened to diligence, before the awful midnight cry be heard,
that so their language may not be, '`Give us of your oil,
for our lamps are gone out.`' I have kept no written accounts of many of the visits;
but some as is above-mentioned, were favoured opportunities;
in others the life was exceedingly low; and to some a lively visitation was renewed,
and received with much tenderness.
O, may it please the God of all mercies to fix his gracious renewed call,
that it may be like a nail in a sure place.
May the inhabitants of this land be awakened to their proper business,
and so work in the vineyards of their own hearts,
that if calamities should overtake them,
they may be sheltered under the Almighty`'s wing.

"`The 22nd.--I have been very poorly with a violent cold and soreness in my chest,
so that I was much weakened, and was led to look towards my everlasting home:
and I should, I believe, have been well content to lay down my natural life,
had it been my dear Master`'s will.

"`We finished our laborious service at Waterford, the 29th of the tenth month,
through the renewed help of gracious Goodness,
whose condescension was great in opening states,
and giving ability to speak to them in his love,
so that I hope many were led to view their undone condition without a Saviour.
May it prove lastingly profitable to their poor never-dying souls.

"`We went to Clonmel the 30th, and the next day the province meeting began:
the sitting in the morning was much favoured.
The 1st of the eleventh month, at the close of the meeting for worship,
began that for business.
My mind was much impressed and awfully covered,
and as matter opened I was led to express it,
pressing some who had entered into covenant with God, to keep their covenants.
The meeting was much broken, and a solemn covering over it.
When the business was finished, my spirit was led to supplicate the Almighty,
and the meeting ended in a solemn, tender manner.

"`The 5th of the eleventh month, we came to Cork, the 6th was the week-day meeting,
and the 9th, we began the arduous service of visiting families in this city;
sat with five,
and I hope we may humbly acknowledge that our good
Master was pleased to give us the earnest-penny.
One of the visits was a memorable opportunity;
the descending of Divine love did so cover and baptize,
under which a renewed visitation was extended.
May it be closed in with; for if such seasons are slighted,
in which Divine mercy is so bountifully bestowed,
surely it must add to the weight of distress in a day that is hastening.

"`The 16th.--We have sat with twenty-four families,
and have had humble cause to admire the Lord`'s goodness,
who has been pleased to be near, strengthening to labour,
to deal very plainly with the lukewarm, and to warn the disobedient,
also to comfort some poor mournful travellers.
I was one evening so fatigued, and had taken so little proper nourishment,
that I was very faint, and seemed as if I was going home;
but my spirit was clothed with such a heavenly sweetness,
that I believe all would have been well with me.
O, my soul, mayest thou keep near to thy dear Redeemer; that when the time,
the solemn time, doth come, thou mayest be centered with him in everlasting rest.

"`26th. We have had forty-six sittings, very close labour, and many deep baptisms;
but may thankfully acknowledge our heavenly Father has been mercifully near,
opening the states of many, and renewing a gracious invitation to divers.
Some, I hope, will close in with it.
O, may his offers of love be as bread cast on the waters,
that may be found after many days.

"`At Cork, Youghal and Bandon together, we had about two hundred sittings;
but what swelled the number was,
that I was not easy without visiting those who might be termed the outcasts;
for when reduced very low, I received this command.
Gather the scattered, in a manner that deeply contrited my spirit:
and we may with reverence acknowledge,
that the gathering arm of Divine love was wonderfully manifested,
to the tendering of many of their minds, so that great contrition appeared.

"`We left Cork the 9th of the second month, 1785, and came on the 10th to Clonmel,
where was Mehetabel Jenkins from Berwick, in the state of Massachusetts, North America.
We went with her to a meeting, appointed for the town`'s people at Cashel;
which was a solid time.
After some other religious engagements, we went to Waterford.
My spirit was much affected at a first-day meeting there as I sat in silence,
in viewing some whose minds had been tenderly visited,
but who had not made that improvement that could have been wished.

"`The Quarterly Meeting began the 26th, at which were Thomas Ross and John Pemberton.
At the week-day meeting on the 1st of the third month, my mind was set at liberty.
The 2nd paid several visits and was engaged in close labour;
and the next day left Waterford in company with Thomas Ross and John Pemberton,
and went to Ross, where we had a meeting with the town`'s people, a time,
I hope of profit to divers.
We had also several other religious opportunities there.
Then we attended a public meeting on the way to Hoare-town,
and from thence went to Forrest and Cooladine.
At a meeting held at the last place,
different states were visited under the influence of Divine love,
and it was a favoured season: blessed be the God of Abraham, Isaac and Jacob,
who remains to be with his Israel,
and at times causeth the shout of a king to be heard in the camp.

"`This morning +++[+++the date and place are omitted]
I awoke with the precious feeling of the sweetness of Divine love,
which remained some time without alloy;
and under this covering had an opening of fresh service in this quarter,
which brought my spirit under close exercise.
It was to visit the families.
The 12th, went to Ballinclay, and was the next day at the first-day meeting; a searching,
laborious time.

"`We went the 15th to Ballydarton,
and the 17th entered on a family visit to the meeting at Kilconner,
accompanied by Richard Shackleton.
Some of the visits were seasons of favour,
in which Divine goodness administered his visitations of love in an extraordinary manner.
May the visited keep under the tendering power of Truth, and then, I believe,
some of them will be brought into usefulness in the Lord`'s family.

"`The 22nd.--This morning closed the family visit under
the fresh renewings of the baptizing power of Truth;
and in the evening reached Cooladine.
O, may our minds bow, and reverently worship that awful Being,
who continues to be near his poor little depending children.
29th. Finished the family visit here,
not without having had some deep and painful labour,
though there is a little remnant in whom I believe the true birth is begotten.
May nothing be permitted to wound, or hinder its increase.
I may remark, that my heavenly Father was pleased to own, in a week-day meeting,
with the comforts of his holy Spirit, which I silently enjoyed,
to a greater degree than I have many times known: in which,
under the flowing of the sweet streams of humbling consolation,
I was led to make fresh covenant that, through the aid of his holy Spirit,
I would willingly keep with my dear crucified Lord,
though in a state of continued suffering, while the Seed was there,
not desiring a release; if he would be pleased to sustain and keep in the patience,
to the end.
O, may my spirit be so entirely weaned, as only to desire to be what, and where,
best pleases my gracious Lord and Master.

"`The first-day meeting was very laborious, my spirit travelling as under the mountains;
but I felt engaged to stand up under an awful covering, and the power of Truth spread,
to the baptizing of the meeting; and I believe I closed while life was at the highest,
and the sweet savour of it remained on my mind for sometime after.
The 13th of the fourth month,
we finished the family visit within the compass of Forrest meeting.
Here Richard Shackleton left us.
He had been dipped into those baptisms that fit us for service,
and our spirits were nearly united.

"`The 14th we had a public meeting at Wexford, then went to Ballintore,
where we visited the families.
We attended a Monthly Meeting at Enniscorthy, and went back to Ballintore;
where at a week-day meeting were divers not of our Society.
Truth owned, and I was led to open how it had been with me,
respecting my concern to come to that land, that we had no outward gain for preaching,
and that I felt the '`woe`' was '`unto me if I preached not:`' I enlarged
on the purity that vessels thus employed should be brought into,
that the wine and oil might pass without mixture.
I also had to treat on the advantage of silent worship.
It was a season of favour, for which,
may all within me bless and praise Him to whom praise belongs.

"`We visited the families of Friends generally in the counties of Wexford and Wicklow,
and felt peace in the review, though deep was our wading, and close the labour,
with renewed baptisms.

"`We reached Dublin the 29th of the fourth month.
The Half-year`'s meeting began the 30th, and concluded the 4th of the fifth month.
I was strengthened to perform what appeared my duty, to the peace of my own mind.
On the 4th, under the sweet savour of uniting love,
we parted with dear Mehetabel Jenkins, Richard Shackleton and some other Friends,
who were going the next morning for England: soon after,
my dear companion was seized with a violent suffocation,
so that if she had not been speedily relieved,
it appeared likely that she would have been soon removed by it.

"`After this, we were at Mountmelick, and paid a family visit there,
having about fifty sittings, some of them close searching seasons.
Dear Mary Ridgway belonged to that meeting, to whom my spirit was nearly united.
We returned by Ballitore and Baltibois to Dublin, and were at several meetings.

"`On the 7th of the sixth month, my spirit bowed, and was bound up in dark deep silence;
and my mind was greatly affected lest I had offended my God,
and I humbly desired to understand in what; but I was awfully and sweetly answered thus,
I am in the thick darkness, as well as in the light.
The next day we left Dublin.`"

It may be added, that when she delivered up her certificate to her Monthly Meeting,
which was in the eighth month, she bore testimony with reverent thankfulness,
to the mercy and goodness of the Almighty; by which, she said, her companion and herself,
through many deep probations, had been endued with help and strength,
to discharge their duty to his praise, and to their own peace.
