== Chapter VI.

[.chapter-synopsis]
* Visits Hampshire, Kent, Surry, Somerset, Devon, Dorset, Cornwall
* A Written soliloquy
* Visits the Northern and Midland counties
* Extract of a letter
* Visits families in Hants, Eastern, Northern, and Midland counties
* Second family visit at Sheffield, and at Kendal
* Family visit at Birmingham.

Sarah Stephenson does not appear to have travelled much during the remainder
of the year in which she closed her engagements in Ireland.
In the year 1786, she had a certificate for the purpose of visiting Friends in Hampshire,
Kent, Surry, and parts adjacent, with the families in some places.
In the course of this journey, she attended the Yearly Meeting,
and had Mehetabel Jenkins for a companion through Kent,
and the adjacent county of Sussex.

In 1787 she travelled twice with certificate.
The first journey was chiefly in Somersetshire,
and in divers places the visit was extended to families.
The other engagement was in Devonshire, Cornwall, and Dorsetshire.
In this visit also, she was concerned at times to go from house to house, and Ann Byrd,
already mentioned, bore her company in the three counties.

The year 1788 was marked with more extensive travels; but, previously,
her mind had been much stripped of consolation, and enveloped in dismay.
Such an event would naturally tend to keep it humble,
and to prepare her for further service.
The following notice of it, penned the 21st of the second month, shows, in some degree,
for words paint feelings but feebly, the depth of her distress, her continued patience,
and the administration of help in the needful time.

"`My mind having been for some time deeply led, as in the valley and shadow of death,
so that I much feared I had some way or other greatly offended my good Master,
many were my searches; but Oh!
I could not say with David, '`When I go through the valley and shadow of death,
I will fear no evil;`' for many were my fears, and the greatest was,
lest I should never again experience the lifting up of the
light and life of his glorious countenance upon me.
But this morning, being gathered into solemn stillness, my soul fell; these words,
'`My words, they are spirit, and they are life;`' and they proved so to my poor spirit,
which was then permitted in some degree, to see the usefulness of these baptisms,
not only to myself,
but in order to feel with and speak to others who may be alike proved; and who may hear,
in this valley the roaring of the beasts of prey.
These are deep felt truths, to the poor in spirit.`"

In the sixth month,
she received her Monthly Meeting`'s certificate to
visit Friends in the Northern and Midland counties,
also in Scotland; and it had the addition so usual in those lately granted to her,
of her view of visiting in some places the families of Friends.

She has left a very short account of this long journey; and indeed she performed it,
comparatively, in a very short time; for she was at home in the eleventh month.
Her former companion, Ann Byrd, went with her as far as York;
and then Esther Brady (already mentioned by the name of Esther Marshall) joined her,
and they went together through Scotland.

A short extract from a letter, written at Edinburgh, on this journey,
will show her humble disposition,
and in the scarcity of information relating to this engagement,
may be acceptable to the reader.

[.embedded-content-document.letter]
--

"`I have had renewedly hitherto, on this journey,
to admire His love and great condescension in helping me along,
so as to leave the places in general peaceful: a favour beyond the expression of words.
Indeed, I cannot but humbly admire his goodness afresh, being often led to feel that,
'`My father`'s family is poor in Manasseh, and I am the least in my father`'s house.`'`"

--

When she attended the Monthly Meeting on her return, and gave back her certificate,
she informed her friends that in the course of her visit, from meeting to meeting,
she had been led to trust in that Power,
which appeared at first like a grain of mustard-seed,
but which enabled her fully to discharge her duty.
She also expressed her compassion for the low circumstances of many Friends in Scotland,
and her belief of the need of thankfulness on the
part of those who were in more easy situations.

Two religious engagements employed a part of the year 1789;
in which she had the accustomed certificates of the concurrence of Friends.
First, accompanied by Ann Byrd,
she attended the Welch Yearly Meeting held that year at Breckon.
Then returning through Herefordshire, they visited the families of Friends at Leominster;
and after calling at Worcester, and visiting several meetings in Gloucestershire,
she arrived at home after an absence of about two months.
Her other engagement was a visit to most of the families of Friends in Hampshire;
and Mary Merryweather, a promising young woman in the ministry, since deceased,
was her companion.

She was at the Yearly Meeting both in 1790 and 1791;
but previously to that in the latter year,
she had obtained a certificate to visit some families of Friends in Wales.
Her own short memorandum of the journey only mentions those of Pontypool, Monmouthshire;
after which service she went to the Welch Yearly Meeting, held that year at Builth,
in Brecknockshire.

A longer journey was now to be accomplished,
though the season of the year might seem ill adapted to the frame of a tender female.
It seems however,
that the clear call of religious duty silenced subordinate considerations,
and our friend had long been endeavouring in simplicity to follow that holy Leader,
who can make hard things easy.
In the tenth month she obtained a certificate to visit Friends in some of the Eastern,
Northern, and Midland counties, and the families in some spots.
Her own words, with little variation, may relate the accomplishment of the undertaking.

"`I left home the 21st of the tenth month, 1791, with my beloved companion Ann Byrd,
and got to Marlborough.
The 22nd, after an opportunity with a widow Friend there, we rode to Hungerford,
at which place we had a sitting with two Friends, and then went to Newbury.
First-day, the 23rd, was at a favoured meeting,
and a sitting at a Friend`'s. In the afternoon we rode to Reading.
The 24th, we went to Staines, and the next day were at a meeting there,
owned by the Master; also had two opportunities in Friends`' families.
The same evening we went to Brentford.
The 26th, we were at a meeting there, the forepart of which was very exercising,
but it ended comfortably.
Afterwards we rode to Islington, and lodged at Mary Sterry`'s.

"`On the 27th we had a humbling tendering opportunity;
the next day rode to Stansted Mountfitchet in Essex,
and were the day following at a meeting held in silence, and deeply exercising;
but we had two opportunities in the Friends`' families, which much relieved our minds,
and then we went to Saffron Walden.
The 30th, being first-day, we were at the two meetings,
and three opportunities in Friends`' families.
The 31st we were at a meeting at Thaxted, very close and exercising; but I was enabled,
under the authority of Truth, to clear my mind, and felt comfortable.
After dinner, we had a baptizing time, to the tendering of all present,
and then rode to Dunmow.

"`The 1st of the eleventh month, we had a meeting at Felsted,
and on the 2nd one at Stebbing, attended with deep travail of spirit,
under the feeling of a lukewarm disposition, inattentive to the business of salvation;
and for the awakening of such,
we were enabled to labour closely under the influence of that love,
which desires that all may be gathered.
After dinner, we were favoured with the extendings of heavenly goodness,
under which we parted, and rode to Bardfield, where George Gibson and Susanna Day,
from Walden, came to us on the 3rd, and we had a favoured meeting.
They accompanied us in paying two or three family visits.
The 5th, we dined at a Friend`'s house, where we had a searching opportunity,
then rode to J. M`'s. and spent seventh-day with them.
On first-day, we went to Chelmstord, and sat the two meetings,
which were laborious and exercising;
but we had one or two opportunities in Friends`'
families which were relieving to our minds,
so that we left the place easy.

"`The 8th, we arose early, and went to Boreham to breakfast,
where we had a comfortable but closely baptising opportunity,
and then went to an appointed meeting at Witham, very deeply exercising:
more humility and spiritual labour were wanting; but Truth arose,
and we felt humble thankfulness.
The 9th, we had an appointed meeting at Maiden, where many Friends met us,
and several of the town`'s people came, and the scholars of a girls`' boarding school.
It was a memorable day.
The blessed Truth reigned, both at meeting and in an opportunity at the inn,
where twenty or more Friends were present.
It was a day that called for reverent thanksgiving to the Author of all good,
unto whom all praise belongs, and unto poor mortals, abstracted from heavenly goodness,
only blushing and confusion of face.
The 10th, at Kelvedon, we had a sweet, silent meeting, also some family sittings;
and the next day a meeting attended with close labour,
under the feeling of a lukewarm spirit being too prevalent.
On the 12th, was a meeting at Coggeshall,
large and mercifully owned by our great and good Master.
It ended with solemn supplication.
We had also several other favoured opportunities, and left the place peaceful.

"`The 13th, we went to Colchester, where we found dear John Kendal weak and poorly;
but I believe sweetly alive in the immortal life.
The next day we were at the two meetings, which were deeply exercising,
and did not tend much to the relief of our minds.
The next morning we had a sweet opportunity at a girls`' boarding school,
and went forwards.
On the 16th, we were at a meeting at Colne, a time of deep exercise.
Here our beloved friend Mary Brightwen, of Coggeshall, met us,
whose company we also had at some other places.
She is one who lives near that pure fountain,
which preserves us fresh and living in the best life.
We had two favoured opportunities, and then rode to Halsted; and on the 17th,
were at a meeting there, and at several family opportunities,
in which the offer of holy help was extended.
The 18th we went to Haverill, and the next day in a meeting there, had deep wading,
but Truth arose,
and it ended with thanksgiving and praises to Him who is forever worthy.

+++[+++Being now in Suffolk]
"`We went on the 20th, to Sudbury, and the next day attended the two meetings.
At the afternoon one was a burial, and they were both owned,
as also were several opportunities.
Samuel Alexander, of Needham, in this county, met us here,
and his company was truly acceptable.
On the 22nd, he accompanied us to Ipswich, where we rested the next day,
and had a tendering opportunity with some Friends in the evening.
The 24th, we were at meeting, and a time of renewed favour it was.
My mind was deeply baptized,
and I had sensibly to perceive that there was a renewed visitation
to a man Friend there on whose head I thought I could lay my hand.
It was a day to be remembered.
The individual above alluded to was much tendered.
I hope it will be made profitable to him, and that he may make covenant, and keep it.

"`After meeting we had a sweet tendering opportunity at our lodgings,
where several Friends were present;
and in the afternoon we went home with Samuel Alexander to Needham.
The 25th we went into the country to visit an infirm woman,
and in the afternoon to see William Crotch and his family,
where we had an uniting season, not soon to be forgotten.
The following day we were at the meeting,
in which a little bread was handed to the poor and needy,
of which number there were some almost ready to faint.
The passage respecting the poor widow, who was gathering two sticks,
to bake a cake before she and her son died was revived, as applicable to a state,
or states, then present; and I believe it was made a season of encouragement to some.
We had some uniting opportunities at that place, I hope not soon to be forgotten.

"`On the 27th, accompanied by Samuel Alexander, we set out for Brandon,
and were the next day at a laborious and deeply exercising meeting.
Here some Friends from Bury met us.
The 29th, we rode to Wareham in Norfolk,
and had a comfortable baptizing season in a Friend`'s family there.
That evening we went to Wisbeach in Cambridgeshire.
About seven miles of the road was, I think, one continued mire,
so that our horse was in danger of being set fast,
but we were favoured to get safely through it.
We went the same evening to Gedney, in Lincolnshire,
where our kind friend Samuel Alexander left us.
The 30th we were at meeting there,
which was a season of encouragement to the few who belonged to it;
we also had a tendering cementing time, before we left the place,
and then rode to Spalding.
On the 1st of the twelfth month, we were at a meeting there, pretty large,
and for a time very exercising;
but the covering of Ancient Goodness gradually spread over us,
and it was an encouraging time, as well as a close one.

"`On the 2nd and 3rd, we were riding to Broughton,
and the meeting the next day was small, owing to the inclemency of the weather:
it was silent and deeply exercising; but an opportunity which we had in a family,
tended much to the relief of our minds, and I believe to the comfort of some,
whom we left under the precious feeling of the Father`'s love.
That afternoon we rode to Newark in Nottinghamshire, eight miles,
the weather being very cold and snowy, and the next day, over the forest, to Mansfield.
The snow was so deep, that we had much difficulty in getting along;
but through the goodness of our gracious Helper, we came safely.
The 6th, we were at a meeting at Mansfield, I trust to satisfaction,
and afterwards rode to Chesterfield.
We had a meeting there on the 9th, comfortable and refreshing to our spirits,
and I hope to others.

"`The 10th we went to Sheffield,
and the next day entered on the close and laborious service of visiting families.
We had above one hundred sittings and casual opportunities.
The number was increased by extending the visit to those that were disunited,
and to such as attended meetings, though not joined in membership with the Society.
I think we might thankfully acknowledge that gracious
Goodness afforded help from day to day,
and covered our spirits with his gathering love; so that when close things were spoken,
they did not seem to be spurned at.

"`We closed the service on the 9th of the first month, 1792, and left Sheffield the 11th,
in near unity, I believe, with the truly living among them.
On the 12th, we reached Stockport in Cheshire,
and the meeting there was a baptizing season.
The 15th we attended a meeting at Newton, which is a small one, on the forest,
and in a very cold exposed situation, and no house near.
Our minds were dipped into sympathy with the few Friends belonging to it.
May such as are differently situated prize their privileges,
and not neglect the attendance of meetings through small matters,
or slight indisposition.
From thence we went to Sutton, where the meeting was rather small,
but owned by the Master by the extendings of holy help,
in order to strengthen the little that remains that is almost ready to die.

"`Next day was a meeting at Frandley, pretty large, a low and wading time,
but I hope not without profit to some present.
After meeting we went to Warrington, in Lancashire, and on the 17th, attended a marriage.
In the afternoon we had a favoured opportunity,
in which a precious visitation was renewed to divers present.
The next day we had a meeting with Friends, a time of favour,
and of tender visitation to backsliders.
On the 19th, was a meeting at Ashton, a time of deep wading,
but it ended under the feeling of life; and on the 20th, one at Langton,
I hope to profit.

"`The 21st, we were at a meeting at Preston, deeply exercising;
but some select opportunities were to satisfaction.
The 22nd we went to Lancaster, and rested a few days at my dear cousin Sarah Dilworth`'s,
with whom and her daughter, we were refreshed with the descendings of celestial dew,
from Him who regards the dust of Zion, and satisfies her poor with bread.
We also attended the week-day meeting, which was exercising,
there being but few deeply travailing baptized minds,
but many revolters who are laying the reins as on the neck, and going whither they list,
and others in a lukewarm state; so that when Jerusalem is searched as with candles,
what must be the portion of these?

"`From Lancaster we went to Kendal, my mind being under close baptism,
having long had a prospect of again visiting families there;
and this appeared to be the right time.
With the unity of Friends there, we entered on that weighty service,
and though deep wading and frequent baptisms were our portion, yet,
we had thankfully to experience the arm of sure help to be near for our support,
and to supply for the service of each day.
To Him praise and thanksgiving belong, now and forever!
Thus, through the renewings of holy help, we were enabled to go through the service,
under the covering of that love which seeketh to save,
and also to bring back those that are gone astray.
I think we had about ninety sittings; and parted with the living among them,
under the sweet feeling of that unity,
aptly compared to the ointment poured on the head of Aaron,
that ran down the beard and to the skirts of the garment.
There is a precious remnant of the living upright-hearted in that place,
and they have a mournful allotment.

"`From Kendal, we went to Yelland, Wray and Settle,
and were at first-day meeting at the last named place.
The prevalence of a lukewarm spirit was painfully to be felt; but there is a remnant,
who I trust are like the few in Sardis, whose garments were unspotted.
May the humble diffident minds be strengthened.
+++[+++We had now entered Yorkshire]
and proceeded from Settle to Airton, and Skipton,
where formerly lived that honourable man in his day, David Hall.
We had a searching time there;
but an invitation to the Fountain of purification was given,
and some consolation to the poor travellers Zionward, was handed forth.
From Skipton, taking one meeting by the way, we went to Rawden;
and had deep wading at the meeting on first-day,
but after a considerable time of starving that thirst for vocal
ministry which is painful to rightly exercised ministers.
Truth arose.

"`We went the same evening to dear Christiana Hustler`'s, near Bradford,
and rested two days, as both of us were poorly in health.
It was comfortable being with Christiana and her daughters;
and several Friends came to see us, with whom we had some favoured opportunities.
We afterwards took meetings in our way to Chesterfield,
and from that place proceeded pretty directly to the Quarterly Meeting held at Birmingham.
We also visited the families in that place, from which I returned home,
and reached Melksham the 23rd of the tenth month, 1792.`"
