== Chapter VIII.

[.chapter-synopsis]
* Two memorandums
* Journey to Wales
* Extract of a letter
* Yearly Meeting
* Three memorandums
* Visits Ireland again
* Her letter relative to that subject
* Short account of the journey
* Letter from Cork
* From Castlebank
* From Rathfriland
* Extracts from others
* Paper found without date.

During the interval between the eastern journey related in the foregoing chapter,
and one taken in the same year in nearly an opposite direction,
our friend was favoured with the experience related in the two following memorandums:

"`Mellisham, 16th of Sixth month, 1797.
This morning, when alone, my soul was sweetly, unutterably so,
overshadowed with the love and precious presence of the Beloved of my soul;
who was pleased to break in upon it with the effusion of adorable kindness;
under which I was enabled to supplicate the King of kings,
through the medium of the pure Spirit of his Son, the Lamb immaculate,
for preservation and ability to such a poor despicable worm,
to do whatsoever he might be pleased to employ me in;
and humbly to crave preservation through this vale of tears; and at the close of time,
that my poor spirit, through his adorable mercy, might be granted admittance,
where forever I might worship Him, with the Lord Jesus.
Amen.--This, after a time of deep baptism.`"

"`1st of Eighth month, 1797.
This morning,
sweetly opened into the Divine mystery of the coming of the adorable Son of the Highest,
with the salutation of the angel to the mother of our dear Lord,
attended with the precious feeling of his pure redeeming love to mankind,
in order to purify, so as to make meet for union and communion with Him while here,
and everlastingly to dwell with Him in a glorious eternity.
O, my soul, mayest thou ever reverently worship and adore, with awful fear,
the King of kings and Lord of lords, who is forever worthy,
and is still permitting babes and sucklings to bless and praise his holy name.`"

Her next journey was into Wales, and Mary Jefferys was again her companion.
North Wales was a principal object; but the families of Friends of Worcester,
and a few meetings in Warwickshire, were included in the prospect.

[.offset]
The following extract of a letter written at Pontypool,
will show her feelings at the outset.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
30th of Ninth month, 1797.

My spirit rejoices at being favoured with the unity of the brethren.
It is a great strength in low dipping seasons, which are often my portion.
We have now entered the principality, cousin Mary Jefferys and myself;
and our kind friend Joseph Naish, of Congersbury, in Somersetshire, has, I think,
freely given up to accompany us into North Wales.
The prospect of this mountainous country, the season of the year,
for my poor creaking tabernacle, is not without discouragement;
but I endeavour to look from them, and as much as possible,
humbly lean on Him who is strength in weakness, riches in poverty,
and a true helper in the needful time, to the poor little ones, that trust in him,
and +++[+++have]
not in all the earth, any thing that they desire in comparison of him.

--

In the twelfth month, she had accomplished her visit,
and intimated to her Monthly Meeting that she had been divinely
helped to pursue the prospects before her.
The lonely situation of Friends in North Whales, seems to have excited her sympathy,
as was the case on a former visit,
and she reminded her friends at home of their superior accommodations,
as a cause for gratitude on their part.

She attended the Yearly Meeting in 1798,
which is the only journey of which there is any account:
but the following are interesting memorandums of that year.

"`10th of second month, 1798.
My mind was sweetly consoled, after a season of deep hidden conflict, only known to Him,
who sees his poor, mournful, stripped ones.
But forever blessed be his holy name, who continues to be, to the wrestling mind,
a refuge-tower, a place of defence, where, in the appointed season, bread is given,
and water is sure.

"`28th of second month.
This morning hope was comfortably renewed,
in the continuation of the heavenly Father`'s all-sustaining, protecting,
directing power, after a time of close trial both of body and mind.
In unutterable condescension, I was also given to taste of the sweetness,
of which the safely landed are in the full possession;
and an humble hope was raised that, through adorable mercy, I shall,
when my conflicts are ended, be permitted to live in his holy presence forever.

"`22nd of tenth month, 1798.
Yesterday I was sixty years old.
O, that the few days that may be added to my exercised allotment, may be spent,
according to my small measure, to the honour of my blessed Lord and Master,
who hath graciously been near for my help and support,
from my infant years to the present day; that gratitude and humble dedication,
may be the constant companions of my tried mind;
that I may not in seasons of close besetment, when fiery trials may surround,
let go the anchor of hope and confidence in Him who hath been near in six troubles;
and that a grain of living faith in his adorable mercy may be granted,
that he will support in the seventh.
Thus, O Lord, be pleased to keep to the end, that at the end, through thy adorable mercy,
my spirit may be admitted within the gates of thy holy city,
forever to live in thy presence.
Thus, O Lord, be pleased to do for me, one of the least.`"

In the second month, 1799,
she applied for a certificate for the purpose of again visiting Ireland.
Ireland was then the scene of civil war,
which rendered the prospect of travelling in it alarming to her natural fears.
The following letter to her relation, Joseph Storrs, of Chesterfield,
will show the manner in which it affected her.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Melksham, 21st of Second month, 1799.

[.salutation]
My beloved cousin,

I received thy truly acceptable lines.
Indeed I think it a favour to be remembered by my beloved friends;
and it is particularly so in low proving seasons,
when the billows seem ready to overwhelm: which has been,
and is yet at times the case with me,
under the present prospect of what I apprehend is required duty.
It is to visit the nation of Ireland, a prospect truly awful,
as well as hazardous in various respects, under which nature shudders;
but may He who has an undoubted right to send by whom it pleaseth him,
keep my eye and heart mercifully stayed upon him in simple faith, love and obedience;
so that if unmerciful men should be permitted to inflict hardships or death,
if but the best life is preserved, it will be an unspeakable favour.

I have had this prospect many years, and for the last twelve months,
I did not expect so long a suspension; but of late time +++[+++the concern]
came so heavy, with a belief that I must no longer delay, that,
at our last Monthly Meeting, I spread my prospect before Friends: under which,
I believe many minds were brought into near sympathy.
As going out of the nation requires the approbation of the Quarterly Meeting,
should no obstruction arise, and my feeble frame be enabled to move,
it cannot be before the latter end of next month.
My beloved relations, I have no doubt of having your tender sympathy;
and I also crave your prayers for the preservation of my best life;
and that the cause of Truth and righteousness may not in any wise suffer through me--not,
if the mighty ocean should prove my grave.

[.signed-section-closing]
I remain your nearly affectionate, exercised cousin,

[.signed-section-signature]
Sarah Stephenson, Jr.

--

She received in the third month,
a certificate of the full concurrence of Friends of her Monthly Meeting;
yet solicitude for her personal safety engaged the minds of many.
She was herself also not wholly free from apprehension.
It was therefore thought not unsuitable that some
Friends should meet and have a serious conference,
in order to consider the right time for her to set forward on her journey; which,
as has been said, wore an aspect of some peril.
They met accordingly,
but the result of their deliberation was a belief that it
was best to commit her to the protecting care of the Lord,
who had thus called her forth into religious service;
and whose tender mercies are over all his works.

The account which she has left of this journey is short, and except as to the voyage,
far from being so circumstantial as the interest which the reader may probably feel,
would induce him to desire.

"`The 10th of the fourth month, 1799, I left home with my former dear companion,
Mary Jefferys, Jr.,
under the awful prospect of paying a religious visit to the nation of Ireland,
if the way should open,
and it should appear practicable in the perilous state of things in that land.
In the way there, we attended a Quarterly Meeting at Shrewsbury,
to a good degree of satisfaction.
We proceeded the same day, and the 20th, reached Holyhead to dinner;
and about nine o`'clock the same evening went aboard a packet for Ireland.
A little before we left the inn an awful but sweet covering spread over us,
under which we were baptised, so that fear was much taken away,
and more than usual strength seemed afforded in the needful time.
It is thou,
Almighty Father, who art the supporter and preserver of thy poor depending children,
under the shadow of whose wing is safety in every time of danger.

"`We had rather a slack side-wind, so that the vessel made but little speed,
but rolled much, and we were also becalmed about two hours,
when I was affected with sickness, yet not to so great a degree as at some times.
But He in whose hand the winds are,
was mercifully pleased to keep my mind in such a
state of calmness as calls for reverential thankfulness.
About eight o`'clock, on second-day morning, the 22nd, we landed at Dublin,
attended the Yearly Meeting there, which began the 27th,
afterwards visited the different meetings of Friends, also families at Cork, Limerick,
Youghal, Moat, Dublin, and Enniscorthy, stayed the Yearly Meeting in Dublin, in 1800;
and then accompanied by our kind friend Joseph Williams of Dublin,
the 8th of the fifth month, went to Waterford.
Next evening we embarked for Milford, where, after a trying passage,
the wind being unfavourable, we landed about nine o`'clock on first-day morning,
the 11th, and had a meeting with the few Friends there in the evening.
Next day, we had an appointed meeting at Haverfordwest,
and then proceeded directly homeward, and reached Melksham the 15th,
after a laborious and perilous journey.`"

Here is the account of a year`'s labour dispatched in a few lines;
but though our friend has been thus brief in description,
the chasm may be well supplied by some letters to her relations,
written during the journey.

[.offset]
The first extract is from one to her cousin, Joseph Storrs.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Cork, 18th of Seventh month, 1799.

For some weeks past, we have been closely engaged in visiting families here;
but as my beloved relations, I know, are much interested in our welfare,
I shall endeavour to give a little account of our movements since leaving Dublin.
We attended the Yearly Meeting, a time of deep exercise;
but gracious help was mercifully granted, for a simple discharge of duty;
but to relate some things respecting this land would
not be best until we may be favoured to meet,
if so in the ordering of best Wisdom.
We left Dublin on the fifth-day, after the close of the Yearly Meeting,
went that day to Ballitore, and the next morning to the Monthly Meeting at Carlow;
a place thronged with military men, and where much blood had been shed;
from thence to Kilconner, and so to Enniscorthy,
where grievous devastation has been made.
We lodged at a Friend`'s house at the foot of Vinegar Hill,
where such numbers of lives were lost;
and the Friend had been taken up the hill by the insurgents,
after having taken leave of his wife and family, expecting to be shot:
but they were not permitted to do him any personal injury.
We went from thence to Ballintore, to Cooladine and Forrest,
where Friends had suffered very greatly in their property,
and had expected to lose their lives.

At one Friend`'s house at Forrest, about eight men came with full purpose to murder,
as was believed, and they queried one of another why they did not begin, saying,
what did they come for.
But as the Friend and the family were with them in the kitchen,
such a calm came over them that it was like a solemn meeting,
so that the men seemed to be chained by a power that they could not account for,
and went away without doing the family any personal injury.
Many women were waiting in the court; ready, as was believed,
to plunder when the men had murdered.
These women seemed much disappointed at loosing the booty.

Many other affecting accounts we had in passing from
place to place through the county of Wexford.
In one place we passed near a barn in which one hundred
and seventy protestants were burned alive;
and we saw hundreds of houses in ruins in passing along.
Though the accounts in England were affecting, (Youghal,
23rd) I think they did not by far come up to what we have heard from Friends here.
The last place we were at in the county of Wexford was Ross,
where the wonderful interposition of Providence was such, that General Johnson,
who was chief in command, said, as I was informed,
that that day`'s work must not be attributed to man, but to the Almighty.
Ross is about eight miles from Waterford.

Before I drop this moving subject,
it seems right to mention the wonderful protecting
arm of the Most High round the members of our Society,
so that none, except one who left the house and fled to arms for protection,
lost their lives in these violent commotions;
though many other innocent Protestants were cruelly murdered.
I have repeatedly had to say,
that the singular protection of Providence ought to be written as with a pen of iron,
and with the point of a diamond on the hearts of Friends, never to be erased.

Our kind friend Robert Fowler +++[+++her townsman, who had gone over with her]
accompanied us, through the county of Wexford to Waterford, where he left us;
and where we stayed nearly two weeks, and made many calls, like visiting families,
as far as it went.
The next place was Clonmel, where we stayed about a week,
and were employed in a like manner, though not in a regular one.
The next place was the meeting at Garryrone, and so to Youghal, where we stayed six days,
and were not wholly idle.
The next place was Cork, where a partial visit would not be accepted;
and though the prospect was deeply affecting, yet as it appeared the way to peace,
we entered on the arduous service in humble fear, and went through about eighty visits;
but the Quarterly Meeting for Munster coming on, to be held at Youghal,
it seemed right to attend it, and we have left the rest of the families until our return.

Being now at Youghal and the Quarterly Meeting over, I think we may thankfully say,
that the Master graciously condescended to own, with his good presence,
in this day of danger and dismay.
The children`'s safety depends, on all occasions,
on their going down to the valley and choosing the smooth stones for their slings,
and then waiting for holy direction and power to convey them.
O, may I be preserved through the perilous day in this land,
and every future day of my life, if many days are allotted me by Divine Wisdom;
though that does not seem very likely,
for my frame seems considerably shaken since I came into this land.

--

The following extract of a letter written on the way from Cork to Limerick,
and at the latter place, gives an account of the completion of the family visit,
and of her final farewell to the Friends of Cork.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Casllebank, 9th of Eighth month, 1799.

[.salutation]
My beloved cousin,

I now sit down to salute you by a line after the
close of an arduous visit to the families at Cork,
which was much extended by taking in all who attended our meetings,
whether in membership or not.
We have been closely engaged,
and through the renewed daily help of the Shepherd of Israel, were enabled to finish,
the evening before the last; and yesterday attended their meeting,
in which we had to take a sweet and solemn leave.

--

[.offset]
After some further narration not material to insert, she adds,

[.embedded-content-document.letter]
--

May all within us bless his holy name,
thankfully acknowledging that hitherto the Lord hath helped us;
and humbly beg that he will be pleased to continue near to preserve us,
and direct all our movements, that so they may meet with holy acceptance,
and our spirits be favoured with that peace,
which the world can neither give nor take away.

--

"`Limerick, 11th. We were favoured to get here on seventh-day evening safely,
though a good deal fatigued.
Yesterday we attended both the meetings, and tomorrow is the Monthly Meeting,
after which, I apprehend,
we shall not find ourselves excused without sitting in the families,
which is fresh cause of abasement and reduction to the natural will,
that so much desires to look towards a release,
in order again to meet our beloved friends in our native land.
But as we came not in our own wills, but I humbly trust, in the Master`'s,
may it be done in and by us through time; and then,
the various cups assigned us being drunk (which at times may seem mingled very bitter,)
we may hope that adorable mercy will permit our spirits to rest forever with him,
in his blessed kingdom, where no alloy is known.
This will be an ample reward for every season of conflict.`"

The following breathes the true language of consolation,
and shows that a mind closely engaged in fulfilling its own share of religious duty,
is still open to sympathy for the distresses of others;
its insertion may please and benefit the reader.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Rathfriland, 19th of Eleventh month, 1799.

I find it a task to address my beloved cousin, after an event that so nearly affects her,
and in which I am a large sharer.
But resignation to the Divine will is our duty, under the consoling evidence,
that my beloved friend and relation is taken from a scene of pain and trial,
to a place in that glorious kingdom where no alloy is known,
forever to rest with him whose glory the heaven of heavens cannot contain.
These considerations forbid +++[+++us]
to mourn; though to feel when such tender ties are broken, I trust,
is not displeasing to him who wept over Lazarus, especially when +++[+++we are]
enabled reverently to say, thy will, O gracious Father, be done.
May these dispensations of unerring wisdom,
be a means of more closely uniting our spirits to Him, who is the way, the truth,
and the life;
that so we may more feelingly know that our '`Redeemer
liveth:`' and that because he liveth we live.
May I think nothing hard that my gracious God may be pleased
to order for me in this wilderness and vale of tears,
that so, when my measure of suffering is filled up,
my exercised spirit may rest with Him who has been near in six troubles,
and I humbly hope will not leave in the seventh;
and may his ever blessed arm of help and tender succour be near,
for thy preservation and support.

--

The remaining extracts are from letters to Joseph Storrs.
They conduct the reader through much of the remainder of the journey,
and show the state of her devoted mind at its close,
when safely returned to her own habitation.
The letter which first occurs has several dates.
It was begun in Ulster province, and finished at Dublin.

[.embedded-content-document.letter]
--

My dear cousin`'s truly acceptable lines have lain
much longer unanswered than has felt easy to me;
but the frequent and deep baptisms that have been my portion
in this land and particularly in this province +++[+++Ulster]
have rendered my mind unfit for saluting my beloved
friends in a manner that I would desire to do;
though I think they were never more dear to me than since leaving my native land.
I desire not to utter the language of complaint with regard to my sufferings;
but for the cause, and them that make it suffer, I mourn.
I desire I may patiently drink what further cups may be assigned to me,
and be willing to suffer with the Seed, which is indeed sorely oppressed.
But under all, my dear cousin, the Good Shepherd has been pleased to be mercifully near,
to enable in a good degree to discharge what has appeared to be required duty;
though my passing along has been as under the mountains,
and fears have at times so taken hold of my poor mind, as to doubt of living through:
and indeed my frame is weakened considerably since being here;
but with this I am not dismayed, if the best life is but preserved.
The Quarterly Meeting for Ulster is coming on,
after which I hope we may soon feel a release from this province, and go to Dublin,
which is in the province of Leinster, where are four meetings unvisited.
I hope we may look towards our own dear land,
with a belief that we have endeavoured to do what we could,
and if it be the blessed Master`'s will to bring us over the great deep in safety,
that all within us will be enabled to bless his holy name.
But I dare not build upon, or much please myself with, the hope of a speedy release,
though not without a little or faint expectation of it.

My beloved cousins, you are near to me,
and I do believe I am favoured to have a place in your remembrance
with desires for my preservation every way.
May the God of all grace be with you and yours, and with us poor pilgrims;
and if he see meet to favour us to meet in mutability,
I humbly hope it will be with thanksgiving and praise to his holy name.

Dear Charity Cook +++[+++of South Carolina]
is confined here with the small pox.
They have been out three days, and not a large burden,
and at present no unfavourable symptoms appear.

Stranmore, 29th of eleventh month, five miles from Lurgan,
where we intended to go tomorrow, to attend the Quarterly Meeting.
We are returned from the Quarterly Meeting and found dear Charity very ill,
the doctor doubting her getting over that night,
but yesterday and today the disorder seems more favourable.

6th of twelfth month.
The attendance of the Quarterly Meeting, with some other meetings there,
was closely exercising; but I trust we were in our right places,
as on my return I felt peacefulness; and as to great things I do not expect them,
being one of the little ones,
but desire to be faithful to what the Master may be pleased to require,
though through very deep baptisms,
which indeed has been the case in the attendance of this Quarterly Meeting.

Dublin, 11th of twelfth month, 1799.
We got here last evening much fatigued.
We left Charity Cook with the appearance of a favourable recovery.

--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Enniscorthy, 4th of Fourth month, 1800.

The cause of my not writing arose from a hope of a more speedy release from this land;
and though the detention has been long,
and much increased by the large field of labour in Dublin,
yet I dare not question the propriety of it;
as I had painfully to taste what the consequence of omission would have been.
The service was very arduous, extending to comers to meeting, and disowned persons,
so that with these and the members we had more than two hundred and thirty sittings;
which were not finished before sixth-day week in the evening;
and we left Dublin next morning for the county of Wicklow, where we had not been.
There are but few of our Society.
We are now in the county of Wexford, on a family visit at Enniscorthy.
I had a view of it when we were here before, but that did not seem to be the time.
I expect we shall get through this, and I hope some other little service,
so as to get up to Dublin, to the Yearly Meeting;
after which I humbly hope and expect we shall set our faces homewards,
which is truly desirable;
but above all things that He who hath mercifully been with us hitherto,
will be pleased to continue with us to the end of our labours here,
and accompany us with his good presence to our native land;
that his preserving power may keep us to the end of our pilgrimage,
and that when time ends, our spirits may forever rest,
in joyful peace and holy consolation.

My beloved cousins, if in the ordering of best wisdom, we should meet in mutability,
it seems very desirable;
but at times I feel an increasing desire for a greater
degree of resignation of my own will,
that the great Master`'s will may be more perfectly done in and by me.
I feel little ability for writing; but on looking over our travels in this land,
which seem now to be winding up,
and how our gracious holy Helper has been near to preserve and give ability
to perform what little services he was pleased to require of me,
it humbles all within me, and leads reverently to bless his holy name:
breathing in humble fear at the footstool of his awful Majesty, this language,
I am but an unprofitable servant.

Farewell my beloved relations.
May the God of all grace be with and keep you and us while on earth,
and cause us to meet again in uninterrupted peace, joy, and holy consolation,
is the humble breathing of your nearly affectionate, exercised cousin,

[.signed-section-signature]
Sarah Stephenson.

--

[.offset]
The following was written from Melksham in the fifth month.

[.embedded-content-document.letter]
--

I have thankfully to commemorate the goodness of adorable mercy,
in carrying us through so arduous a journey, I hope safely in all respects;
and have now to look back with a peaceful evidence
of having been in the line of required duty.
But though I trust this is the case, I know I am one of the weaklings of the flock,
and have nothing whereof to boast.
And indeed I have often wondered that such an one as I, should be called forth;
and when I look around, and see many whose abilities are so great,
it sinks my mind into admiration of condescending goodness to make use of me.
May I, during the few fleeting days that are yet ahead, be enabled so to steer,
that my poor little bark may arrive at the haven of rest.

--

[.offset]
The materials collected afford nothing for the remainder of the year, but the following:

"`28th of the eighth month, 1800.
This morning sweetly refreshed with the precious streams of pure consoling love,
strengthening and encouraging my drooping, exercised mind,
to an increasing trust in that mercy and power that
hath in many seasons borne up my head,
when the waves of deep baptism and sore conflict seemed ready to overwhelm,
and made way amidst opposing spirits,
that seemed ready to defy the armies of Israel`'s God.`"

As the reader is now advancing towards an end of the relation
of the various exercises of this dedicated Friend,
in her native land, the following paper, found without a date,
may in this place engage his perusal with acceptance.

"`I went to the funeral of a beautiful young plant in a neighbouring county.
She was about eighteen years of age.
My mind was much impressed in the meeting with this language,
'`Blessed are the dead that die in the Lord,`' etc., and with it I stood up.
Life mercifully attended, to the tendering of many minds, and to the peace of my own.
I felt a desire to stop a few days with the family,
and had some satisfactory opportunities.
On first-day, I felt some movings on my mind to be at a meeting a few miles distant;
and the father and one of the sisters of the deceased accompanied me.
As I rode along my mind was drawn into an abstracted state,
so that I felt an entire detachment from visibles,
and as though I had no connections on earth; and I was much absorbed in Divine love,
in which my spirit humbly rejoiced.
Under these heavenly feelings, I rode a considerable way; but of this sweet enjoyment,
I felt an abatement, and was gradually centered in a state of great poverty,
in which I went to meeting.
And as I sat, though in great weakness, the state of the meeting was opened before me,
and I had to see the states of many individuals;
but for a considerable time felt no commission to move, until a Friend,
who did not belong to that meeting, appeared.
I then felt the movings of life, and when he sat down, it seemed my place to stand up;
and utterance was given, and the baptizing power of Truth was felt,
to the melting of many spirits present; and to the great abasement of my own before Him,
to whom belongs all praise, thanksgiving and honour, who is forever worthy.`"
