[short="Testimony of Philadelphia Meeting"]
== Testimony of the Monthly Meeting of Philadelphia, for the Southern District, held the 26th of the first month, 1803, respecting Sarah Stephenson.

We are engaged to give a short account of our beloved deceased friend, Sarah Stephenson;
who, with the concurrence and unity of the Monthly Meeting of Wiltshire,
the Quarterly Meeting of Gloucestershire and Wiltshire,
and the Yearly Meeting of ministers and elders in London,
embarked on a religious visit to Friends in North America.
She arrived at New York in the eighth month, 1801,
and although frequently under bodily indisposition,
engaged in a family visit to Friends of that city,
which we understand she was enabled to perform much to their satisfaction.
After this service, feeling her mind drawn towards Philadelphia, she,
with her beloved companion, Mary Jefferys,
came to this city on the 9th of the second month last, much indisposed; she was,
nevertheless, enabled to attend divers of our meetings,
in which she was engaged in the exercise of her gift, to edification and comfort.
After some time,
she opened a prospect of visiting the families of Friends of this meeting,
which was cordially united with: she had not proceeded far in this service,
before her indisposition increased so as to confine her to her chamber.
During her illness, some account was taken of divers lively expressions,
which may afford encouragement and benefit to survivors, viz:--She said to a Friend,
"`I am now in my sixty-fourth year;
thirty of which I have been closely engaged in endeavouring
to fulfill my little mission--If I had but one talent,
as I have endeavoured to improve it, I hope I shall be accepted.`"
The Friend remarked, that her bed had been made in sickness: "`yes, said she,
wonderfully so.`"
Being asked how she felt herself respecting her recovery; she answered,
"`I have no prospect of it: I believe I have finished the work.`"

And at another time--"`There is nothing in my way but my dear child,`" meaning her companion:
then, addressing herself to her, added, "`but, my dear,
thou had nothing else to expect when we left home:`"
then said as a consideration that comforted her,
"`It is a favour I shall leave her amongst Friends who will extend their tender care.`"
Upon its being proposed she should take something, she said,
"`my friends propose things which I sometimes comply with,
but it seems precious to look towards a release.`"
After a time of stillness, she said to her companion, "`Oh! my dear,
I have been sweetly comforted in my good Master`'s presence.`"
She frequently acknowledged the kindness of her friends,
and expressed her desires that the Lord would reward them,
and often mentioned how quiet she felt.

At another time she said,
"`It gives me no pleasure when any one speaks of my recovery being likely;
I have a humble hope it would be well, if it pleased my good Master to take me now;
and if I stay longer, it cannot be better--I have no desire for continuance here.`"

The last day, 26th of the fourth month, early in the morning,
the conflict of nature increasing, she said, in a patient disposition,
"`This is wearing work:`" after a coughing fit, being much exhausted, "`It will be well,
let it be which way it may; and that is better than all the world.
It seems as if it must be nearly over now,
I have so little strength left;`" then making a little pause,
seemed to be uttering praises--`" How good!
How good!`"
After awhile she said, "`I cannot say much, but my King reigns.`"
Soon after which, she quietly departed this life, in a full assurance of a happy change;
leaving a sweet memorial in the minds of many of those who had opportunities
of observing her humble deportment and instructive conversation.

Her body, after a season of solemnity, was interred on the 29th day of the fourth month,
1802.
