== Preface.

It seems desirable that the following accounts, left by Sarah Stephenson,
of her life and religious engagements, showing the sufficiency of that grace,
by which she was what she was,
may tend to the encouragement of others to walk by the same rule,
and to mind the same thing, namely, the revelation of the Divine will.
Conducive to this is that waiting on the Most High,
to which belongs the promise of a renewal of strength, of running without weariness,
of walking without being faint; which was much the experience of this beloved Friend.
And though many and deep were the baptisms, on her own and others`' account,
in order that Truth might be exalted in the earth,
yet the sweet and frequent enjoyment of Divine peace was her abundant reward.

May the perusal of these memoirs so affect the youth, into whose hands they may fall,
with the love and admiration of Christian virtue, as to raise a heartfelt petition,
similar to that which Sarah herself, when a child, was engaged to put up,
when she was reading the lives, and happy conclusions of the faithful:
"`Often,`" said she, "`have I been led to make a pause, and crave of my heavenly Father,
be pleased to make me like unto these your servants,
whatever my sufferings in this life may be.
If you wilt be with me in the way that I go, give me bread to eat, and raiment to put on,
you shall be my God, and I will serve you.`"
Thus making and keeping covenant in early life,
she witnessed the declaration to be fulfilled, "`Godliness is profitable to all things,
having the promise of the life that now is, and of that which is to come.`"
Frequently in the decline of life,
when engaged to speak of the goodness of Israel`'s Shepherd,
she had encouragingly to testify that he had not only graciously fed and clothed her,
but had been with her through all her life; and she earnestly desired that others,
for themselves, might taste and see that the Lord is good.

As many of those to whom she has expressed this desire,
will probably peruse her fragments,
and thereby afresh recollect her labours of Gospel love towards them,
it may be profitable for such to examine how far the designed purpose has been answered,
as it respects each of them,--whether, unhappily,
the visitation of heavenly kindness has been only as a morning cloud,
and as the early dew, that goes away; or whether it has been abode under and improved,
so that an account of it, and of other favours,
may be finally given up with joy and thankfulness
to the Giver of every good and perfect gift.

These memoirs were left in detached pieces, and consequently,
though each might be valuable, they did not form a satisfactory whole.
This deficiency is attempted to be supplied by private information,
by searching the records of meetings and by other means,
and the editor has sometimes taken the liberty of
a little varying the phrase of the parts,
where the narration runs in the first person; and now and then of supplying a few words.

[.signed-section-context-close]
8th of the First month, 1807.
