== Chapter II.

[.chapter-synopsis]
* Visits Cumberland
* Western counties
* First engaged in a family visit
* Goes to the men`'s meeting at Lavington
* Exercises and relief, with reflections
* Death of a young child, a relation
* Account of meetings in Wiltshire.

It appears by the foregoing relation,
that Sarah Stephenson first appeared as a public minister in Worcester in the year 1767,
and in the twenty-ninth year of her age.
She was then a member of the Monthly Meeting of Hardshaw, in Lancashire,
of which Liverpool meeting forms a part; but she was recommended the same year,
by a certificate of removal, with her mother, to the Monthly Meeting of Chippenham,
in Wiltshire, in the compass of which was Sutton Benger,
the residence of her uncle John Fry.
Of this Monthly Meeting she had not been long a member,
before she applied for its concurrence in a service which lay before her.
This was doubtless her first application of the kind, and the meeting,
adverting to what may be called the infancy of her ministry,
certified that she had lately appeared in a short but lively testimony;
that she was in good unity,
and that her life and conduct corresponded with her appearance and profession.
The certificate, which was granted in the third month, 1768,
was addressed to Friends of Worcester, or elsewhere,
yet she has not left an account of her visit to them,
but relates the other part of her errand, nearly in the following words:

"`In the spring, 1768, my mind was strongly impressed with a sense of duty,
to visit the meetings in Cumberland, my native county.
Accordingly I set forward and got safe to Lancaster, and from there to Carlisle,
where the Yearly Meeting, for the Northern counties, was held.
I had the company of my dear cousin William Dillworth, Sarah Taylor of Manchester,
and Esther Tuke of York.
The latter intended after the Yearly Meeting was over,
to visit the meetings in the county; and, being informed of my prospect,
kindly took me under her wing, and was indeed a tender mother in the truth.
After her return home, she wrote me an instructive and affectionate letter,
signifying she felt the lack of my company after I had left her.
This tended to strengthen my mind in humble hope that my moving was in His counsel,
who leaves not his little striplings, as they confide in him alone,
and keep under his holy government.
I returned pretty directly home, with sweet peace of mind.`"

In the year 1769, she attended the Yearly Meeting, and visited meetings in Essex.
She met there with tender sympathizing Friends; but says,
the greatest of all favours was that of having the company of the Ancient of Days,
who was mercifully near to help, and afforded strength to answer his own requirings.

"`In 1770, I visited, she continues, the counties of Somerset, Devon, and Cornwall.
One night I slept in a damp bed, which much affected my health.
When we got to Kingsbridge, (for it seems she had a companion,) I was very poorly;
but being at the house of William Prideaux, his wife,
who I believe was a faithful servant of Jesus Christ, was affectionately kind, and,
being dipped into the low and closely exercised state of my mind,
was made a messenger of consolation to me.
She was one of those who sat much at her dear Lord and Master`'s feet.
With him, she was frequently permitted to sup,
and I believe he many times supped with her,
supporting her exercised and deeply proved spirit.
In this journey, He who opens and none can shut, was many times near,
to support and abilitate to do what he was pleased to require,
for which and his abundant goodness many ways, may my spirit ever love, fear,
and obey him, for He is worthy forever.`"

For this journey, she had the certificate of Chippenham Monthly Meeting,
which was granted in the eighth month, and returned in the twelfth.
The year 1771 must therefore be assigned for her first employment in a
service in which she was during the remainder of her life so much engaged,
namely, the visiting of Friends in their families.
The origin of this, she describes nearly as follows:

"`A very close exercise came now on my mind in a line in which I had not been engaged.
He who is pleased, in condescending love, to open to the understandings of his children,
his blessed will, through the Spirit of his dear Son Jesus Christ,
our Mediator and Advocate,
was pleased to lay a concern on me to visit the families of Friends at Melksham,
a line of service then so new, and particularly so in this country, that I apprehend few,
if any, could remember a visit of this kind having been paid in it.
From a view of being such a poor, weak, and contemptible instrument,
I frequently adopted the language of Gideon,
'`I am the least in my Father`'s house;`' and from an apprehension of great unfitness,
was very desirous of being excused,
endeavouring to persuade myself that the Lord would remove the concern from me; till,
in compassionate regard, he was pleased to administer sickness,
and to allow distress of mind to attend.
In this time I was brought very low, and, in my own apprehension,
had every symptom of a decline, except a cough;
so that I looked for the messenger of death,
with a desire to pay the debt due to my friends, by a sacrifice of life.
But, oh,
when I looked up with desire of beholding the gates of mercy open for my reception,
it seemed clear to me, that if I did not obey the discovery that had been made,
it would remain, as I then saw it,
a total obstruction to my soul`'s entering into the blessed kingdom of eternal rest.
This awful distressing prospect reduced all within
me into resignation to his blessed will;
and then the smiles of his favour arose upon my spirit,
and strengthened me to move under the influence of his love.
I laid my concern before Friends, and way was opened for my moving in this weighty work;
which the Lord graciously owned by his blessed Spirit, from family to family:
and I may thankfully acknowledge that the minds of Friends
were generally open to receive what I had to communicate;
so that I had cause to bless and praise the holy name of Him who lives forever.

"`This was the beginning of a work in which my good
Master has since been pleased often to employ me,
which has been very arduous, through deaths often and deep baptisms:
I think scarcely any service so much so; but he leads down to the bottom of Jordan,
in order to qualify to feel the different states of individuals in families,
and in this abased state to speak as the Spirit gives utterance.

And, for these humiliating labours the reward is sure, and preciously sweet;
though not always given in our own time, but in the blessed Messiah`'s,
which is the best and right time.

"`In the morning, 28th of the second month, 1771, as I was musing,
a state of dejection covered my mind,
so that I was fearful I should become a prey to the enemy of my soul;
and was deeply humbled,
and an ardent prayer was raised to the Father and
Fountain of strength and wisdom for preservation.
And He was pleased in love and great condescension,
to convey to my soul the sweet overshadowing power of his love,
for which may all within me bow, and in fear and reverence, bless his holy Name.`"

"`The men`'s Monthly Meeting (for at this time we
had no women`'s) being to be held at Lavington,
the 6th of the twelfth month, 1771, a weight rested with me for some days,
with an apprehension that I must attend it;
but a clear sight of its being the requiring of heaven,
and the overshadowing of the Divine presence and love, were withheld.
Though I sought with fervency of spirit, for Divine direction, it was still withheld;
I believe, to try whether, like Saul, I would go forth without it; which I dared not do,
so I concluded to stay at home.
But about an hour before the time of setting out, it pleased Infinite Goodness,
in great condescension, to cover my spirit with his love,
and with indubitable certainty of its being his requiring,
to which all within me was subject; and gratitude overspread my soul,
humble praises ascending from my lips.`"

The reader may now perceive that a connected narration is not to be expected.
Probably the author of the memorandums, which are offered to his perusal, might,
in making them,
intend them rather as helps to her own recollection of past instances of Divine support,
than as materials for a journal.
The lack of exactness in arrangement cannot now be supplied,
and the following remarks are here introduced without the
certainty of their being placed in due order of time.

"`My spirit has been, for a considerable length of time, baptized,
and in much pain and distress, by day and also by night,
and that sweet calm which I had before often felt when I awoke, was withdrawn;
a serenity in which my mind felt and understood that declaration,
'`The angel of the Lord encamps round about them that fear him,
and delivers them.`' Instead of this, pain was now administered; in this trying season,
all comfort was withdrawn; the stone was heavy on the well`'s mouth,
and I was sensible of but little strength to roll it away.
Language fails me to express the painful feelings of my mind; but,
O! the invisible Power, who was pleased to permit me to be thus tried,
gave me to behold the unsafety of drawing my comfort from visible things;
and the secret manifestation of help was mercifully afforded,
to apply with a broken heart and a contrited spirit,
to Him who holds the winds in his hands, and causes them to blow where it pleases him.
In this state was brought to my remembrance that text,
'`The kingdom of heaven suffers violence,
and the violent take it by force.`' My mind was led deeply to consider an awful eternity,
and the purity that is necessary for the inhabitants of the new Jerusalem.
These considerations, with indisposition of body, greatly humbled my mind,
with this attendant thought,
perhaps kind Providence is opening the eye of my
soul more clearly into things of this nature,
that I may be prepared for my final change.

"`Second month, 1772.
My cousin Jeffery`'s daughter Catherine was taken ill, and remained so several days.
She was a child uncommonly ripe for her age.
+++[+++Probably not more than four years old.]
The sweetness of her disposition was extraordinary, and her patience in sickness,
very instructive.
I waited much upon her, esteeming it a favour,
because of the sweet covering that attended,
and particularly so when her innocent spirit departed.
I think I never experienced anything to equal it, on a similar occasion.
She died on my lap; at which time Divine love, in an uncommon manner, covered my spirit,
and boundless Goodness gave me to feel beyond what I can or dare express,
being permitted to behold her rest, and taste her joy, in unutterable bliss;
which reverently bowed all within me in awful prostration
and thanksgiving before Him who is glorious in holiness,
and fearful in praises, and does wonders.`"
