== Chapter III.

[.chapter-synopsis]
* Visit to Wales, Cheshire, Lancashire, etc.
* To Dorset, Hants, London, etc.
* Dorset and Somerset
* Circular Meeting
* London
* Family visit in Wilts
* Devonshire and Cornwall
* Indisposition and exercise
* Family visits in London
* In Bristol.

In the fifth month, 1772,
Sarah Stephenson obtained the certificate of her Monthly Meeting,
for the purpose of paying a religious visit to Friends in Wales, Cheshire, Lancashire,
and some adjacent counties.
In the course of it,
she was again employed in the weighty service of visiting the families at Lancaster,
and her relation William Dilworth of that town,
a Friend in the ministry already mentioned, bore her company in that engagement.
She returned her certificate in the eleventh month of the same year,
and acknowledged that she had been favoured with Divine regard in the visit,
and that she had peace and satisfaction in giving herself up to the service.

The next year there are no traces of her having been exercised in travelling,
until the eighth month;
when she laid before her Monthly Meeting her concern to visit Friends in Dorset, Hants,
London, Essex, and adjacent places.
Having obtained the concurrence of the meeting,
she set forward and was soon engaged in a family visit among Friends at Shaftsbury,
Dorset.
Her engagements of this kind did not finish here;
she was alike employed at Witham and Colchester, in Essex, and at Norwich;
and she visited meetings in Dorset, part of Hants, Essex, Norfolk, and part of Suffolk.
She returned by London, and through a part of Oxfordshire;
and on giving up her certificate in the third month, 1774,
expressed her great satisfaction.

In 1774, she accompanied Jane Shipley, a Friend in the ministry, of Ashmore, Dorsetshire,
in a visit to Somersetshire, and part of Dorset.
In the early part of 1775, she was unwell;
but on reviewing her late engagements in the discharge of apprehended duty,
she felt comfort and peace; of which she gives the following account.

"`Felt some bodily complaints, which in my apprehension seemed alarming;
but the covering of inexpressible sweetness was spread over my mind,
with a sense of its being a taste of the reward which the Lord will give for faithfulness.
Encouragement thus sprung in my soul,
with hope or belief that my late engagements relative
to the church met with Divine approbation.
This, succeeded with tender love to the whole race of mankind,
sweetly consoled my drooping spirit.
Under this Divine influence, if consistent with the will of my heavenly Father,
it would have been comfortable to have quietly departed;
but if it is his pleasure to continue my stay here a little longer,
I humbly hope he will be pleased to condescend to direct my steps;
and then I ask no more but, at last, a sweet admission into rest.`"

In the ninth month, this year, she had a certificate to attend the Circular Meeting,
to be held at Coleshill, in Warwickshire.
The meetings thus denominated were annually held in one of the seven counties of Warwick,
Worcester, Gloucester, Hereford, Somerset, Devon and Cornwall.
They were chiefly large public meetings for worship,
attended by persons of other religious professions,
and also drew together no small concourse of Friends.
They have since been discontinued by direction of the Yearly Meeting,
and the last of them was that at Gloucester in 1786.

In 1776 she again yielded to a concern to visit the meetings of Friends in the metropolis,
and was at the Yearly Meeting.
In London she had for a companion Esther Marshall, of Leeds, in Yorkshire;
but here they parted, and Sarah, going into Essex,
visited the families of the Monthly Meetings of Coggeshall and Felsted.
She then returned to London, and afterwards visited the meetings in Hampshire;
in which county she was joined by Mary Powell, of Nursted, near Devizes.
About this time Elizabeth Merryweather, of Rumsey, Hants,
daughter of Samuel and Deborah Waring, of Alton,
was concerned to visit the families of Friends at Fordingbridge and Ringwood,
in that county, and at Poole in Dorset.
Sarah found her mind engaged to join her in this visit; which she accordingly did,
and afterwards returned home by way of Shaftsbury.
The certificate which she had obtained for this visit,
had been addressed to Friends in London and parts adjacent.
On her return in the tenth month,
she gave an account of the different parts which she had visited,
and though some of them
must have appeared to be rather beyond what might be called adjacent,
her account was satisfactory to the meeting.

The year 1777 was a busy one with our industrious friend.
In the first month she laid before her Monthly Meeting a concern,
which although it was one of those she esteemed arduous, did not occasion a long journey.
It was a family visit to Friends in Wilts, the county of her residence.
In the third month she informed the meeting, the concurrence of which she had,
that she had paid the visit pretty generally; and that,
though the task had been laborious,
it had been accompanied with a good degree of satisfaction.
These are her words; and they form a phrase not uncommon among us.
The critic may cavil, and call in question their accuracy;
but the humble diffident servant of the Lord will thankfully
receive whatever degree of joy he may be pleased to afford,
as the reward of service, and say it is enough.

Our friend had no sooner given in her report of this visit,
than she spread before the meeting a prospect of another,
which had for some time engaged her mind.
This was to visit Friends in Devonshire, and the families of Friends at Plymouth,
adding that she apprehended this service would be succeeded
by an engagement of duty to visit Friends in Cornwall.
The meeting concurred, and she visited in her way most of the meetings in Dorset.
Arriving in Devonshire, she had Ann Byrd, of Uffcolme, for a companion,
and they visited the meetings and most of the families in that county.
She also had the company of this Friend to the families
of two of the three Monthly Meetings in Cornwall;
and in one of these, that of Catherine Phillips, of Redruth,
already mentioned in this narrative by the name of Catherine Payton, of Dudley.
In the other Monthly Meeting, she went generally alone, as to an outward companion; yet,
on returning her certificate in the tenth month,
she reverently confessed that she was not destitute of Divine help,
which was sufficiently afforded to enable her to pass through the laborious service.

On this journey she was favoured with the views and
feelings related in the following account.

"`1st of eighth month, 1777.
This morning poorly in health, and feeling myself very unwell,
was led to look towards an everlasting abode.
Under this view my spirit was greatly broken and tendered with the love of God,
so that I felt a willingness to leave this world,
if he was graciously pleased to prepare me for his holy rest:
and the view of being taken off, though far from my dear relations, did not seem hard,
provided I might be received by Divine mercy.
But though, under this awful heavenly covering,
there appeared some of the true gold or right weight, in me,
yet I saw there needed more of the consuming fire of God.
This caused a fear, lest,
when I was brought to the balance of the sanctuary I should be found lacking.
But my spirit was so enclosed in Divine sweetness, that, with brokenness of heart,
I was enabled to adore my Maker, and pray for the continuance of his mercy and judgment,
that thereby my soul might become so refined, that when it pleased him to say,
"`Time here to you must be no longer,`" I may not be found lacking; but,
through the deep in-working of his holy Spirit, and the abounding of his mercy,
forgiveness and great lovingkindness,
through the mediation of our dear Lord and Saviour, Jesus Christ,
I may be favoured with admission into his holy kingdom,
there to sing the song of the redeemed.`"

In the two following years we again find her occupied
in the engagement of visiting families.
Early in 1778, she set out for London,
having first obtained the certificate of her Monthly Meeting,
and visited the families of the Monthly Meetings of Gracechurch street and Ratcliff.
Esther Marshall was her companion in these visits, and at least in the former,
Deborah Townsend of London.

She acknowledged on her return, that through the daily renewal of Divine help,
they were enabled to perform that laborious work;
although she hinted at the deep baptisms,
which fell to the lot of such as were engaged to visit the Seed, because it lies low,
and is much oppressed.

In the first month, 1779,
she informed her Monthly Meeting of a concern to visit the families
of Friends in the large meeting of the city of Bristol.
Her account at giving back her certificate was,
that they were enabled through Divine help, to perform the service to their own peace;
and she added that, if they had obtained any crowns they cast them down,
with humble adoration, at the throne of the Almighty; to whom belongs, said she,
the power, thanksgiving, and praise, now and forever.
