== Chapter IV.

[.chapter-synopsis]
* Visits Leicestershire, Nottinghamshire
* Families at Sheffield
* Ackworth school
* Ill at Leeds
* Visits families there, and at Lancaster
* Thomas Gawthorp
* Westmoreland, Cumberland, and Scotland-families there
* And at Newcastle, Shields and Sunderland
* Mabel Wigham
* Visits Durham
* Families at Kendal
* And a second time at Lancaster
* Coalbrookdale and North Wales
* A meeting in a graveyard, Builth
* Three of her written memorandums.

Early in the spring of 1780, Sarah Stephenson set out, with due credentials,
according to the good order of the Society, on a long journey,
which took up not only the remainder of that year, but much of the next.
The relation of it, for the most part in her own words, is as follows:

"`I left Melksham the 14th of the fourth month, 1780, accompanied by Jane Shipley,
and went by way of Cirencester, Odington, Stow, Shipston, and Warwick, where,
and at some other places, we had meetings,
and reached Coventry the 24th. Next day we had a meeting there, in which Truth arose,
and different states were spoken to, in a good degree of authority.
In an opportunity after dinner, heavenly goodness broke in,
and we had a sweet open time together, under the renewings of life, in which we parted.
We went that afternoon to Hinkley, had a meeting there,
and reached Leicester on the 26th. My mind was low,
and dipped under the feeling of the oppression of the pure Seed,
through the prevalence of a wordly spirit.
The 27th, in a meeting there, I had very close labour, but a little life arose;
and after dinner, many Friends being present, we had a tendering opportunity,
which a little relieved my mournful spirit.
The 28th we had a meeting at Loughborough, and afterwards rode to Castle Donington,
to see our dear friend, Ruth Follows.
Then we went to Nottingham, and were at the two meetings there,
on first-day the 30th. In the afternoon Truth spread.
We also had a tendering opportunity at John Leaver`'s, in the evening.
The next day we went to see the widow Coulson, who seemed in a sweet tender frame,
and not far from her last and safe home.
Oh, how comfortable it is to see greenness in advanced age!
We had also other opportunities in Friends`' families to satisfaction;
and in the afternoon we rode to Mansfield, twelve miles, in a very heavy rain.
The 2nd of the fifth month we had a meeting there, rather a healing comfortable season,
after which we went to Chesterfield, and had a meeting on the 3rd;
a few not of our Society attended, and considerable tenderness appeared.
The 6th, we went to Highfield, about one mile from Sheffield.

"`I had, for a considerable time, had a concern to visit families at Sheffield;
and the weight of it increasing, I found it best to open my concern to the elders,
my companion being free to accompany me in this service.
It was united with by Friends, and we began the weighty undertaking on first-day,
the 8th, after the two meetings there.
We had upwards of eighty sittings, besides the usual meetings, in less than three weeks.
The labour was great and the baptisms many, on account of the low state of some,
and the rebellious disposition of others.
Yet there is a faithful living remnant preserved among them,
with whom we were at seasons refreshed,
and had humbly to rejoice in the Lord`'s house of prayer.
The visit was accomplished under the covering of Divine love,
and we left Sheffield peaceably.
May my soul ever be clothed with humble thankfulness to the God of my life,
who has mercifully regarded so poor a creature; unto him belongs all praise,
and unto us abasement and contrition.

"`From Sheffield we went to Thorn;
and stayed a few days to rest at the house of my companion`'s brother.
While there, there was a violent storm of thunder and lightning,
and the largest hail-stones I ever saw.
It was thought some measured three inches round.
The 3rd of the sixth month we went to Pontefract,
and on first-day morning were at meeting there,
in which much close searching labour was bestowed on a revolting people.
We left them under a belief of having faithfully discharged our duty,
and went to Ackworth.

"`We were at the afternoon and evening meetings there,
owned by Him who uttered the language,
'`Allow the little children to come unto Me.`' There was a beautiful flock of children,
near two hundred, in very pretty order.
My spirit was much concerned for their preservation,
and humble cries arose to the Fountain of living mercies,
to favour them with the blessing of life forevermore.
The 5th, in the morning we attended the committee at Ackworth school,
and in the afternoon went to Barnsley, and on the 6th to Burton,
where many of the neighbours came to the meeting, and it was an open favoured time.
The burial ground there is said to be the first that was in the possession of Friends;
and to have been given by a sober man, who was moved with pity,
on seeing a corpse indecently treated.

"`The 7th we went to Wakefield; the meeting there was a low wading time;
but I hope the states of the people were fully spoken to:
in the afternoon we went to Gildersome.
On the 8th, was a silent meeting; but I hope not an unprofitable one.
We had the company of our dear friend Robert Walker.
In the afternoon we went to John Hustler`'s, near Bradford,
and on the 9th had a meeting at Bradford, in which Truth arose,
and we parted under a degree of the Father`'s love.
The 10th we went to Leeds, and lodged at my cousin Gervas Storr`'s,
where I received many marks of kind attention.
I was seized with a violent attack of a complaint in my stomach, which held many hours;
and had not kind Providence been pleased to give a little ease,
it seemed unlikely that I could have continued long;
but He whose ways are ways of wonder, and unsearchable,
has a right to use such means as will most effectually answer the purpose he has in view.
My indisposition brought me very low and weak,
in which state I was made submissive to the requiring
I felt from him to visit the families at Leeds.
This service was entered upon, under the humble sense of the Master being near;
who gives to his little dependent children,
a degree of that faith by which mountains are removed, and hope and confidence increased.
My dear companion and myself went to the families without any other company,
and in the various sittings had to travail deep,
by which various states were measurably opened; and He,
who remains to be the good Samaritan, was pleased to convey,
through his poor unworthy instruments, the searching wine;
giving to declare to some that, if they would sufficiently bear his cleansing power,
the healing oil would certainly be administered.

"`We had to feel for some, who, resting in their moral righteousness,
were in that mournful state of lukewarmness, which is hard to reach;
yet I hope some of these were aroused, at least for the present.
May they not again sink into supineness.
I should not omit mentioning, that, though we had to be deeply baptized for the dead,
there is a faithful remnant, with whom our spirits were refreshed,
being favoured to drink together of that stream that
makes glad the city and heritage of God.

"`We left Leeds the 10th of the seventh month,
under a thankful sense of having been in the way of our duty,
enjoying that sweet reward of peace, which encourages poor travellers to journey on.
We took several meetings in our way to Lancaster;
and in most or all of them we had deep travail of spirit, under a sense of luke-warmness,
and a worldly spirit.
But blessed be that Name who yet supports his depending children, who cry to him,
feeling that they have no might of their own, and that without Him they can do nothing.
In some of these meetings his power raised the dead,
and gave us afresh humbly to bless his holy name.

"`We reached Lancaster on the 20th. On the next day was the week-day meeting,
in which my spirit was dipped as to the very bottom of Jordan.
Under this baptism, it was clearly opened to me that I must visit families in this place.
O! how great was the exercise.
My dear companion was made sensible that a fresh engagement had taken hold of my mind,
but I suffered the discourager to come in,
and gave Friends leave to appoint some meetings forward,
thinking if the concern respecting Lancaster continued, we might return.
We stayed the meetings at Lancaster on first-day, in which we had an open time.
Several states were opened before me, and I was enabled to deliver what was given me,
with strength, and I trust, with life.
The next day, we went to Yelland, and had close labour there; then to Height.
In the meeting there, but little light was to be felt:
my spirit mourns for the lapsed state of the church!
From there we went to Ulverstone, and the next day had a meeting at Swarthmore,
which was a season of deep baptism; but the power of Truth arose,
and several states were visited, the sincere-hearted encouraged, the idle warned,
and an affectionate invitation given to the wandering prodigals.
It was a season of favour.
The next morning we went to Hawkshead, and had a meeting.
It was a low time,
my mind being much depressed and under an increasing
concern to visit the families at Lancaster.

"`We, however, went on to Kendal, and from there I wrote to my cousin William Dilworth,
informing him that we could not proceed without returning to visit the families.
He acquainted the elders with it, and they expressed their unity;
and on first-day he mentioned it at the close of the morning meeting; which,
as we were told,
so affected the minds of Friends as to bring a great solemnity over them.
We stayed the meetings at Kendal on first-day, which were low baptizing seasons,
on second-day went to Lancaster,
and on third-day morning entered on the arduous service before us.
Deep were the baptisms, and close the labour that were attendant, in passing along;
but under all discouragements, we were helped to deal plainly, and to warn faithfully,
as required.
This, through Divine favour,
was often attended with that power which not only chained down opposing spirits,
but broke some of the visited into tears;
for which we were humbly thankful to Him who has the hearts of all men in his hand.
There is also a precious remnant in that place,
with whom our spirits were sweetly refreshed, and from whom we received encouragement.
Having had about seventy sittings we closed the service,
and took leave of them at their weekday meeting, the day following,
under the tendering influence of Divine love.

"`We next went again to Kendal, calling by the way to see our ancient friend,
Thomas Gawthorp, who was confined to his bed, by an accident.
We sat by him to satisfaction.
The heavenly frame of his spirit was to me truly comfortable,
and a belief was fixed with me,
that he would soon be removed from works to a joyful reward.
We afterwards heard that he remained about two months and then sweetly departed.

"`On sixth-day, the -- of eighth month, we were at the week-day meeting at Kendal,
in which strength was given to point out the danger of a worldly spirit,
even among the well-minded, if not guarded against.
Next day we went to Moreland, and had a meeting, in which we were led into close labour,
and to give an awakening call to the lukewarm.
From there we proceeded to Penrith, Terril, Mosedale, Coldbeck and Wigton,
having a meeting at each place, the latter a favoured one, in which Truth reigned.
O, how gracious and good is the Most High, to own, with his life-giving presence,
in order to gather and convince that he delights not in the death of those that die;
but that he would have all to be saved!
My mind was often mournful on account of the state of the church,
and the secret language of my soul was, '`By whom shall Jacob arise,
for he is small.`' We went on to Holm, Kirkbride, Moorhouse, Carlisle,
Sikeside and Solport, in which places we had meetings.

"`The 4th of the ninth month, we set out for Scotland, and on the 6th reached Kelso,
where we had an appointed meeting on the 7th,
a season owned by the Master of our assemblies, who graciously blessed the bread,
and handed it forth,
to the tendering of the spirits of most present before
Him who can bless the provision of Zion,
and satisfy her poor with bread, giving them afresh to trust in his holy name.
From there we went to Edinburgh, and were at the meetings there on first-day,
a close searching time.
The next morning we set off for the north.
Having crossed Queen`'s ferry, which is about two miles over, we travelled ninety miles,
and got safe to Montrose, and from there to Stonehaven, where we had a favoured meeting.
We had afterwards an opportunity with two youths, to whom it seemed a day of visitation;
and indeed we were all tendered together, so that the current of life ran sweetly,
and warning, and caution were also given.
It was a season that I hope will not soon be forgotten.
We parted under the baptizing power of Truth, our own spirits being sweetly refreshed.

"`We then went to Aberdeen and Old Meldrum.
The two meetings at the latter place were large and satisfactory,
many of the town`'s people being there.
I felt a concern to visit the families belonging to that meeting,
with so much weight and clearness, that I dared not omit opening the matter to Friends,
who readily made way; and my dear companion and myself,
accompanied by James Anderson of Kelso, entered on that service.
The number of families was about twenty, part of them scattered about the country.
I think our good Master was pleased to give us an evidence that the engagement was right,
and was near, in his condescending love, to open the states of the different families.
I was led to deal with them in much plainness, under the covering of that gathering love,
which I felt mercifully extended to them.
O, may the labour of the Lord`'s servants,
many of whom have of late been sent among them, be as bread cast upon the waters,
and profitably found after many days.
I believe the good Seed is sown in many parts hereaway.
Whether it may visibly flourish, I leave;
but I believe the veil of prejudice is rent in many minds.
We finished the family visit and returned to Aberdeen with the evidence of peace,
Almighty Goodness having been mercifully near,
in a manner that reduced all within me into nothingness before him,
and led into humble adoration and silent thanksgiving.
May my soul ever live under a lively sense of his greatness, goodness and mercy,
and of my own weakness.

"`After having an appointed meeting at Aberdeen,
a season owned by the Master of our assemblies, we went to Ury,
the place where Robert Barclay, the apologist, formerly lived.
His grandson, Robert Barclay, and his wife, not members of our religious Society,
treated us with much respect.
Then we proceeded to Montrose.
The road was hilly, and the wind high and cold, which made travelling fatiguing,
but I could not think it hard, for as I rode along my cup sweetly overflowed,
so that I was thankful I was there.
May my soul never forget such seasons of favour;
but ever dwell where the Most High condescends to instruct his servants, namely,
in the humble paths of obedience; that so a happy admittance into rest,
through the mercy of our dear Redeemer, may be granted,
when time to me here shall be no more.

"`On first-day we had two public meetings at Montrose,
to which many of the town`'s people came, and behaved well.
In the morning, my spirit was deeply centered and awfully abstracted, when,
after a time of solemn silence, I felt Truth lead forth to public service; and, I think,
if ever Divine Goodness caused the stream of the ministry to flow through me,
it did so that day.
The afternoon meeting was also a season favoured by Him, who continues to own,
of every nation, tongue and people, those that fear him and work righteousness.
It was a day that called for humble thankfulness to the Lord,
who yet regards the dust of Zion, and satisfies her poor with bread.

"`The next morning we set out for Edinburgh.
In our way there we crossed three ferries, one of them about seven miles over.
We had an old leaky boat, contrary winds, and a rough sea;
so that our passage was attended with some danger;
but through the preserving power of Him who formerly uttered the language of '`Peace,
be still,`' we were favoured to get safely on shore after a passage
of about three hours and a half. My dear companion and John Rutty,
(a lad who rode before Sarah Stephenson,) were very sick,
so that they were not so sensible of the danger as I was.
Some of the waves were so great that it seemed as if we should be swallowed up in them.
In this season of danger, an inquiry took place respecting the state of my mind,
and after a little time I felt a sweet covering,
which centered my spirit in resignation to the Divine will,
under which I could do no less than bless and adore his holy name.

"`We arrived at Edinburgh on an afternoon, the next day were at the week-day meeting,
and the following day visited the families.
We had close, painful labour,
as there was in some a sorrowful departure from ancient purity.
Next day we reached Kelso, forty-one miles, and stayed the meetings on first-day:
on second-day set off for Newcastle, and got there on third-day afternoon,
about sixty-four miles.
We were about a month and two days in Scotland,
having travelled about five hundred miles, visited the six meetings,
and about twenty-six families.

"`A concern to visit the families of Newcastle Monthly Meeting came so heavily upon me,
that we laid it before Friends at their Monthly Meeting,
which was held that time at Shields; and we there entered on the service.
Our gracious Father was pleased to furnish with strength from day to day,
so that we got through there in less than a week,
and left them under the feeling of peace, the evidence of having been in the way of duty.
We next visited Newcastle, where are some valuable Friends,
with whom our spirits were many times much refreshed,
and we had some favoured meetings there.
The good hand is at work among the youth, and I think, fitting some for service.
May the good Shepherd preserve them, and not permit the destroyer to mar the work;
but may it go forward to his praise, and to the edification of the church;
that so judges may be restored as at the first, and counsellors as at the beginning.
There are about forty families.
Our dear friend Mabel Wigham, who then lived at Newcastle, told us,
that when she heard of our coming, her prayer, with tears,
was that we might be engaged to visit families in their Monthly Meeting.
She is a noble warrior in the Lamb`'s warfare,
and seems to be more constantly dwelling with her Master than most.

"`From Newcastle, we went to Sunderland, where we were deeply baptized for the dead, and,
thereby I trust, fitted to labour and deal plainly; but we found a remnant,
who retain their integrity.
May they be preserved.
There were upwards of twenty families.
From Sunderland, we visited the meetings in the county of Durham.
We were at one at +++_______+++, in which the lukewarm were warned, and those,
in whose minds tender desires were raised,
were encouraged to press after the further knowledge of God, whom to know,
and Jesus Christ whom he has sent, is life eternal.
Then we went to +++_______+++, where we had a close laborious meeting:
but there are a few who are contending for the faith.
May they be preserved steady.
We had also a meeting at +++_______+++, where some of the professors of Truth seemed hurt,
by giving way to a worldly spirit.
O, what can rouse some from their lethargic state.
May our gracious Leader be pleased to utter an effectual call,
even that power by which Lazarus was raised from the dead;
that they may not sleep the sleep of death.
How can those who, through Divine mercy, have been favoured to taste of the word of God,
and of the powers of the world to come, do less than mourn and pray for such,
when admitted to the throne of grace.

"`At this time the roads were bad, some bogs in the way, and much snow,
which made travelling difficult, and trying to tender constitutions;
but we were enabled to bear it beyond what we could expect, and got safe to Kendal.
Here I felt a necessity to open to Friends a concern that had long dwelt with me,
and many times greatly bowed my mind under that power
which baptized it into obedience to the requiring,
of visiting the families of that large meeting.
In low, doubting seasons, discouragements prevailed; but as I humbly kept to the gift,
and trusted in the giver, strength arose, and measurably dispersed the difficulties; so,
in simple obedience we proceeded in that weighty service.
Our gracious Father, being near, favoured with renewed help from day to day,
and under many deep baptisms, supported our spirits,
enabling us to minister what was opened in the deeps.
We had more than eighty opportunities, some of which, I trust,
neither the visitors nor the visited will soon forget.
May the Lord be praised, who yet condescends to make use of clay.
There is a number of valuable Friends, and some of the youth are promising.

"`We went on to Lancaster and Preston,
and at the last meeting had the company of our friends William Rathbone of Liverpool,
and William Dilworth; and there I fell an engagement to visit the families,
under the influence of that love, which enables to search the camp, and to deal plainly.
Hence, visiting some other meetings in our way, we went to Liverpool.
My mind was dipped very low, and, under deep baptisms, we visited the families there,
in which service Divine help was near, and so we left that place peacefully;
yet with a mournful feeling of the state of things
being more painful than some years before.

"`We proceeded to Warrington, Frandley, Morley, Macclesfield and Leek.
At Morley we had a large exercising meeting;
but I was favoured with strength to discharge my duty honestly.
At Leek I parted with my companion Jane Shipley; and was joined by Martha Routh,
of Manchester, in a visit to the families of Crawshawbooth, etc.
Hence Martha Routh went home, to prepare for a journey with me through Wales.
William Rathbone went with me to Coalbrookdale,
and as I was under a concern to visit the families of that Monthly Meeting,
he felt his mind drawn to join in it.
At the close of that service Martha Routh came, and we went through Wales;
and felt our minds drawn to visit the families of
Friends in the Northern part of the principality.
I reached home, by way of Bristol, in the fifth month, 1781.`"

It does not appear that our friend kept any exact account of her journey through Wales;
yet the following is probably a relation of all the occurrences in it,
which she thought proper to note.

"`From the New Dale we went to Welch Pool, but I was very poorly in health,
having laboured hard, and taken but little rest.
I had also a violent cough, and my mind was dipped very low;
but it was kept in much patience, though the prospect of going among the Welch mountains,
in so poor a state of health, was discouraging.
Martha Routh was also poorly.`"

It appears to have been the time of some Quarterly Meeting, held that year at Welch Pool,
for she says, "`that on the 28th of the third month,
the Select Meeting began at nine o`'clock, in which some close advice was dropped.
At eleven o`'clock was the meeting for worship, in which Truth arose,
the Gospel spring being comfortably opened, by which the Seed was visited,
humble minds encouraged, and the lukewarm warned, in the awful power of Truth.
At one o`'clock was the meeting for business, and at four o`'clock,
a public meeting in the town-hall.`"

"`The 24th we rode twenty-four miles, and visited one family; the 30th to Tyddiny-gareg,
eleven miles, and visited three families, then went to Dolgelly,
and had a public meeting in the evening in the town-hall.
In this meeting Truth arose, but my mind was not clear of the people,
but felt that we must have another meeting, which was a close exercise,
as my companions expressed no concern of that sort.
Before I gave up to mention it, I was quite ill; when on my telling the cause,
they readily consented to stay,
and another meeting was appointed to begin at nine o`'clock on first-day morning.
We had a very solid, favoured meeting, after which my mind was much relieved.
This town is nearly surrounded by mountains, one of which, I was told,
is four miles to the top.`"

This must be spoken of the ascending road from Dolgelly.
The mountain in question is probably Cader Idris,
the perpendicular height of which is about two thousand
eight hundred feet from the level of the sea.
The last named places are in Merionethshire.

"`Those who have not been in a mountainous country,`" continues Sarah, "`I think,
can scarcely conceive the awful appearance which these prodigious hills make.
To think of our fellow creatures being scattered among them,
led me to contemplate on the greatness and goodness of God,
who cares for the workmanship of his holy hand, not only giving them food,
but contentment, and visiting with his life-giving presence,
the greatest of all blessings.

"`After dinner we rode to Llwyn du, on the coast,
where a meeting was appointed to begin at five o`'clock.
The people collected soon after we got there,
and life seemed to spread on our sitting down;
so that I hope it was to many a time of advantage.
The 3rd of the fourth month we went to Machynlleth,
where we were desirous of having a meeting, though no Friends lived there,
and accordingly one was appointed for the next morning at nine o`'clock,
to which many people came.
It was a time, in which, I think, the Gospel power was felt,
and we left the place very peaceful.
We rode that afternoon to Esgalr goch,
and visited the few families belonging to that meeting,
and had also a public meeting with them to satisfaction.
It was here that that worthy servant and minister of Jesus Christ, John Goodwin, lived;
but now the state of things in that principality is very low.
We did nearly sympathize with the few concerned ones,
for they labour under many disadvantages.

"`At Esgalr goch a cloud of distress covered my spirit,
but the cause why I thus partook of the wormwood and the gall, was hidden from me.
In this deep baptism, I felt it was a taste of what our Lord drank so very deeply of,
and I found him near in this suffering state; not to take the cup from me,
but to make my spirit more willing to drink it.
O, my soul, may you love it; for herein stands your fellowship with God,
pure obedience in all things.

"`We next rode eight miles to Llanidloes,
where my dear companion was so ill that her recovery seemed very doubtful.
She was not at all anxious respecting it;
but to me the prospect of losing her in that lonely spot,
seemed a closer trial than that of laying down my own life.
But one morning, as I sat greatly exercised before Him who raised Lazarus from the grave,
I was led into an awful heavenly sweetness, in which I saw,
in that light that is unchangeable, that she would recover,
which greatly consolated my distressed spirit.`"

The three last named places are in Montgomeryshire.
From Llanidloes to Builth, in Brecknockshire,
the distance is not more than an easy day`'s journey;
and the latter town about seventy miles from Bristol,
a journey of a few days might bring her into the neighbourhood of her own habitation.
William Rathbone had kept them company as far as Llanidloes;
and it does not appear that they visited any meeting in South Wales.

That at Builth was a public appointed one,
of which Sarah gives nearly the following account:

"`The 6th of the fifth month we had a meeting at Builth, not in a meetinghouse,
but in a very convenient graveyard.
Notice having been given in the neighbourhood some days before,
many well-behaved people came.
The ground was smooth, and of a gradual descent.
At the upper end was a stone seat all the way along,
and about the middle of it hung ivy like a canopy, under which we sat.
On both sides were stone seats, which were filled by some of the people;
while others sat on the grass.
The weather was very favourable, and beholding the gravity of the people,
and the feeling of solemnity that covered the assembly, bowed our spirits,
and led humbly to implore Him that had compassion on the multitude formerly,
and would not send them empty away,
that he would be pleased to break the bread of life among us, and bless it.

"`A season of favour it was, for the Lord, who hears the cry of his suppliant children,
was graciously pleased to answer our request; for which our spirits were awfully bowed,
and blessed his holy name, who is worthy forever.
When the meeting was over,
a solid elderly man came to us and said--This has been a glorious day.
Indeed the minds of many of them were affected.
We recommended them carefully and quietly to attend to what they felt.
May it please the Lord, in the aboundings of his love and mercy,
so to leaven them into his nature, that they may be sanctified throughout, in body,
soul and spirit.`"

She delivered up her certificate in the sixth month, 1781, when,
as she had done on a former occasion,
she acknowledged the support which she had experienced,
and described the services in which she had been engaged.
She particularly remarked, that she firmly believed the Seed of God was sown in Scotland,
and said that her returning through Wales,
and visiting Friends in their cottages among the mountains,
were as a cordial in her remembrance.

It was probably soon after her return from this long journey,
that she wrote the following memorandum:

"`1781.--As my soul was led into awful stillness and gathered into abasement,
I was favoured to feel that in the quiet attentive state,
the Lord is pleased to prepare the soul to hear the
language which was proclaimed by the angel,
'`Worship God;`'--awfully leading under the covering of the Holy Spirit,
to adore and worship Him, whose glory the heaven of heavens cannot contain.`"

The two following pieces will close all that remains to be added,
respecting the exercises of this devoted servant, in the year 1781.

"`Eleventh month, 1781.
My mind was stripped, and dipped exceedingly low for many days,
so that all Divine comfort seemed to have left me.
Under this proving dispensation I was tempted to believe that I was cast off;
and as this belief prevailed, the clouds of darkness and distress increased.
I then thought I should be thankful to be removed,
if I might but die like the beasts of the field.
But while under this distress, sitting still one evening,
the Lord was pleased to cause a perfect calm to cover my mind,
and brought before me his wonderful preservations and deliverances, one after another,
from my childhood to the present time, as clearly as if written in large characters:
at the beholding of which my soul was humbled, and faith in the mercy,
goodness and forgiveness of God, began to spring up in my soul,
and mercifully caused the clouds of despair to disperse.
I believe my being thus led to feel a state wholly stripped of hope in the mercy of God,
was in order to lead me into tender sympathy with poor souls thus tried.

"`Twelfth month, 1781.
O, that pure stream which is clear as crystal, proceeding from the throne of God,
which impregnates the soul with its precious virtue, by which it becomes heavenly, and,
in time, like the king`'s daughter, '`all glorious within!`' Thus the soul,
being espoused to Christ, how glorious the union!
Happy in time, and unspeakably glorious in eternity, where the heavenly host sing,
glory and honour, riches and power, to the Lord God and the Lamb, forevermore,
world without end!`"
