== Chapter VII.

[.chapter-synopsis]
* Two memorandums
* Visits the North again
* Ackworth school
* Esther Tuke
* Edinburgh
* John Wigham
* Glasgow, Cornwood, and Allandale
* Meetings in Durham and Yorkshire
* Families at Whitby and Scarborough
* York Quarterly Meeting
* Deborah Townsend
* Families at Pickering and Hull, etc.
* A third time at Lancaster
* Families at Liverpool
* Esther Tuke near her close
* Families at Mansfield
* Coalbrookdale
* Ann Summerland
* Extract of a letter
* Visits families in some Southern and Western counties
* A visit to part of the Eastern and Southern counties
* Families at Norwich
* At Lynn and Yarmouth
* At Colchester.

We have no account of further travels during the remainder of the year 1792,
nor of many in the following year;
except that our friend was at the Welch Yearly Meeting, held at Carmarthen;
also at the Essex Quarterly Meeting held at Colchester,
and at some others on her return homewards.

The two following memorandums belong to this year, 1793.

"`21st of sixth month.
Being at Wanborough, I awoke this morning with the sweet impression of these words;
As a tender Shepherd, does He care for his sheep.

"`Twelfth month.
At a meeting on a public occasion, my mind was much exercised,
travailing after a deep centre and lowly waiting,
to get where the counsel of God is opened, either for ourselves, for the people,
or for both; but my exercise being, as I thought, quite unavailing,
my spirit sunk into dejection.
But near the close of the meeting, when mourning as a dove without its mate,
a language was uttered in the secret of my soul, after this manner;
'`You are precious unto me.
I have graven you on the palms of my hands.
Your walls are continually before me.`'`"

Early in the year 1794, she again obtained a certificate for visiting the North;
which journey may be related with small variation in her own words.

"`The 15th of the third month, I set out for the North,
in company with my dear friend Mary Jefferys, jun., of Melksham,
intending to be at the Half-year`'s Meeting in Scotland.
We left Melksham in the morning,
after having been favoured together with the sweet over-shadowings of love,
and after reverent solemn supplication to the Father of all sure mercies;
under which our spirits were united,
and a humble trust raised in the ever worthy name of the all-saving Helper.
We went by way of Hampton, Nailsworth, etc.,
a Friend of Melksham accompanying us as far as Worcester.

"`The 18th, we attended a meeting there, which was a season owned by the Master.
In the afternoon paid a comfortable satisfactory visit to George Becket and his wife.
He was confined by illness.
In this opportunity we were favoured to drink together of the brook by the way,
which truly refreshes the poor weary travellers.
The next day we went to Stourbridge, and the 20th were at meeting there,
in which my mind was led into searching labour, but also in gathering love;
and at the close, solemn supplication arose.
The same afternoon we rode to Dudley.

"`Next day, we were at a meeting there, in which gracious help was administered,
and some close labour extended under the tender covering of love,
and the honest-hearted were encouraged, humbly to persevere.
At the close, the covering of the spirit of solemn supplication was felt,
under which prayer was put up to the blessed Preserver of men.

"`We proceeded to Birmingham, Tamworth, Chesterfield, Sheffield, Warnsworth, Thorn,
and Doncaster, having one or more meetings at each place;
and I was favoured with help to discharge my duty.
At Tamworth, we visited the few Friends in their families.
The 4th of the fourth month, we reached Ackworth, and stayed there some days,
attending the meetings on first-day, and the week-day meeting;
and I felt my mind drawn to have separate sittings with different parts of the family.
Some of them were to sweet satisfaction, particularly that in the girls`' school,
where was a general tenderness.
Oh! there are some, yes, many sweet children!
May they be preserved, is the fervent desire of my spirit!
We also went to the Monthly Meeting at Pontefract,
in which my mind was much exercised in deep travail,
and enabled to labour in a very close manner;
but under that covering that desires all may be gathered,
and the dead in spirit raised from their graves of earthly mindedness,
before the solemn language be uttered, Remove the candlesticks out of their places.
For this, my soul prays.
My spirit felt easy in having faithfully warned them.

"`We then went to York, and were kindly received by dear Esther Tuke and her family.
We attended the two meetings there, on first-day,
and in the evening had a select sitting with the scholars +++[+++of the girls`' school]
in which Esther appeared sweetly in testimony.
From York we went to Thirsk, Stockton and Newcastle.
After we had been at meeting there, being accompanied by two Friends of that town,
we proceeded for Scotland.

"`The 22nd of the fourth month, we got to Kelso, and had a meeting there,
owned by the Master; and the 25th, reached Edinburgh.
In the evening the meeting of ministers and elders was held, and the next day,
the adjourned Monthly Meeting.
On the following day, being first-day, were two pretty large public meetings,
both owned of the Master; and many of the inhabitants came in.
In the morning I was engaged both in testimony and supplication;
and in the afternoon in testimony.
John Wigham was there, and engaged in public labour in both meetings.
He was preparing to go on a religious visit to America; and under this awful prospect,
my mind was led into near sympathy with him.

"`On the 28th, was the Half-year`'s Meeting: first one for worship,
then one for business, and in the evening the meeting for ministers and elders,
all in degree owned.
We had also, after supper,
a heart tendering opportunity with the Friends out of the North, to whom I felt,
or at least to some of them, the flowings of Gospel love, sweetly cementing our spirits.
We afterwards sat with the different families belonging to Edinburgh meeting,
and were also at their week-day meeting, and the 2nd of the fifth month,
set out for Glasgow.
We arrived there the next day, in the afternoon, and the rude rabble followed our chaise,
as we rode along the streets, behaving very unhandsomely,
of which our singular appearance might be the occasion.

"`The 4th we had a meeting with a few who are in part convinced, and some other persons.
It was a season owned by the Master with his good presence,
so that we had cause afresh to bless and praise His holy name.
The 7th, we reached Carlisle, one hundred miles from Glasgow,
and the meeting there next day was a close searching time,
but I felt best help to enable me to discharge what appeared my duty, and was peaceful.
The 9th, we set out for Cornwood and stopped at Haltwhistle to dine,
where a Friend met us, and led our horse in such roads,
as seemed almost impassable for a chaise, on account of bogs;
but we were favoured to get safely to Thomas Wigham`'s that evening.
The next day we rested, and the following day, being first-day, were at meeting,
a time in which I believe many felt something of the power of Truth.
The 12th, we went to Allandale, and though the distance is but twelve miles,
we were four hours or more in going.
The road was so very bad two miles of the way that we rode in Thomas Wigham`'s cart.
One Friend led the horse, and another walked by our side, and often held the cart,
to prevent us from being overturned; but the day was fine, and my mind peaceful,
so that I have seldom had a more comfortable ride.

"`The 13th, we had a meeting at Allandale,
in which different states were opened and spoken to, I believe under the power of Truth,
as it was a favoured season.
The 14th, we went to Newcastle, and the 15th was the week-day meeting,
a season of sweet refreshment, I believe, to the humble travellers,
tending to unite the spirits of some of us.
In the afternoon we rode to Durham; at which place we had a meeting,
exercising and very laborious, among a few who are robbed and spoiled.
We went the same day to Darlington, and on the 18th, being first-day,
were at the meeting there, in which the gathering love of the Great Shepherd was,
I believe, sensibly perceived by many.
On the 20th, was the Monthly Meeting, which we attended, a low wading season.

"`On the 21st, we had a favoured meeting at Yarm, and in the afternoon went to Ayton,
where the next day we had a meeting, in which my mind was much enlarged, I trust,
under right authority.
The 23rd, we went to Whitby, where on first-day,
I went to meeting under a weighty exercise,
having long had a prospect of visiting the families of Friends;
and sitting under deep baptism, after a time I felt it my place to stand up,
and was engaged in testimony;
in the course of which I had to inform Friends of my prospect of visiting families.

"`When we returned from meeting,
I received a letter giving an account of the death of a dearly beloved child, my cousin,
Edward Jefferys, jun., whom I had cared for as a child of my own.
This information deeply affected my natural feelings, but, under the conflict,
a sweetness not to be fully expressed covered my mind,
with a language as though uttered by him, '`Weep not for me,
for I am glorified in heaven.`' Thus my spirit was bowed in thankfulness,
with tears of humble rejoicing.
My mind was so strengthened, that I went to meeting in the afternoon,
and in the evening entered on the arduous service of visiting families,
through the condescending goodness of Him who helps
with his blessed Spirit to tread as on scorpions,
giving a degree of that harmless nature of the dove
which makes way among high and opposing spirits,
and by which, at least for the present, some were brought down.
We also met with some who, like scattered sheep, were very insensible of their loss;
but these were invited home to the true Shepherd`'s fold.
We also met with a small mournful remnant,
who I fear may weaken themselves by unprofitable bemoaning.
We had nearly seventy sittings, besides attending first-day and week-day meetings.
It was a deeply exercising engagement; but through adorable kindness,
we were favoured to close peacefully,
and took leave of them at the last meeting under
the renewed extendings of gathering love.

"`We next went to Scarborough, where we were engaged in the like arduous service.
When we had gone about half through the visit, the Quarterly Meeting at York came on,
and we attended it.
It was very large, and measurably owned by the Master;
but the exercise and depression of my poor spirit was not small,
though I was helped to relieve myself by uttering what seemed my duty to deliver.
Dear Esther Tuke, a mother in Israel, was affectionately kind.

"`At this Quarterly Meeting were Deborah Townsend of London,
and her companion Mercy Ransom of Hitchin, in their way to Scotland.
Dear Deborah`'s state of health was such, that according to human probability,
she was not likely again to see her own habitation;
but her mind evinced a state of resignation and preparation
for what her good Master might see best,
either life or death.
They travelled on, though with difficulty, as far as Edinburgh,
and there Deborah peacefully closed the scene of life.

"`When the Quarterly Meeting was over, we returned to Scarborough,
to finish the family visit there,
in the course of which we had some tendering opportunities
with several who attended our meetings,
though not joined to the Society; and those who were so,
but whose dwellings were not within the precious enclosure,
were called and invited no longer to remain without it, but to return with speed,
while the day of merciful visitation was extended, before the door was shut.
There was also a travailing remnant, which was, I trust, a little strengthened;
and we parted under the feeling of the precious love of Him, from whom all good comes,
and to whom belongs blessing and honour, salvation and praise;
but from the servants the acknowledgment remains to be due,
'`We are unprofitable servants, we have done that which it was our duty to do.`'

"`We visited the few families belonging to Pickering, about fifteen,
and also attended their Monthly Meeting, and then went to Bridlington,
and sat with the few there; also attended the meeting on first-day.
Some sober neighbours came in, whose minds seemed in a seeking state, and who were,
I believe, glad of the opportunity.
Surely the Lord`'s table will be filled, and the descendants of the faithful shut out,
if they turn not in time to Him, who has so loudly called, '`Turn, turn,
why will you die, O house of Israel?`' From Pickering we went to Beverly;
some miles of the way on the sand, close by the sea.
As the weather was fine,
and I had the feeling of that peace which is an evidence
of our being in the way we should go,
it made the ride pleasant.
We had a meeting at Beverly the next day, exercising and laborious.

"`From there we went to Hull, where being joined by Christiana Hustler,
we entered pretty directly on the arduous service of visiting families;
and though the baptisms were many, and the labour deep,
yet merciful help was graciously near, so that I trust some minds were benefitted.
We finished the engagement on a sixth-day evening,
had an appointed meeting the next day for all the visited,
and in the afternoon went to Cave.
We were at the meeting there on first-day, in which very close doctrine was delivered,
for the arousing of the lukewarm careless professors,
to awake lest they sleep the sleep of death.
After this we parted with Christiana Hustler, and went to York,
were at the week-day meeting, a season owned by the Master,
and the next day went to Selby.
M+++.+++ Anderson of Kelso, who was at York, went with us, also Elizabeth Tuke.
Their company was pleasant,
and the meeting at Selby favoured with the descendings of heavenly good.
The next day we went to Leeds, and on first-day attended both the meetings there.
A little strength was given to throw off my burden, and to leave it with them.
The next meeting was Skipton, in which was deep wading and close labour; but Truth arose,
and I trust some minds were strengthened; and to others,
their states opened and the way set forth how and where to apply for saving help:
also the danger of delay.

"`After meeting we went to Settle, and had a meeting appointed there,
in which strength was given to labour, I hope faithfully.
We also had some more private opportunities to a good degree of satisfaction.
We went to Bentham on a seventh-day, and on first-day were at meeting there,
a close searching time, but favoured.
In the afternoon we went to Lancaster,
under the prospect of the arduous service of visiting the families of Friends there,
which was performed; and Oh, the deep baptisms,
through which my soul passed while so engaged, the Master only knows.
We had upwards of ninety sittings,
besides attending their first-day and week-day meetings.
There are many in this place,
who have '`waxed fat and kicked,`' and forsaken the Rock of their salvation;
unto whom the offers of mercy were afresh extended, on the terms of true repentance.
There are a few who see the disordered state of things, but sink under discouragement.
May He who was with little David enable them to put on strength in his eternal name,
to search and cleanse the camp.

"`Having, I trust, been enabled to divide the word aright, we left Lancaster peaceful,
and went to Preston.
We had a meeting with the few Friends there.
The spring of life seemed low, though I believe there is a little exercised remnant.
From Preston we went to Liverpool,
with a prospect of engaging in the service of visiting families;
and the Quarterly Meeting to be held there approaching,
I had a strong desire to get as far through the visit as possible with propriety,
before it came on; and feeling the blessed Helper near,
I too much forgot my own feeble frame, which was much worn down;
so I was at last obliged to lie by, just as the Quarterly Meeting came on;
and I was confined to my chamber,
which occasioned considerable delay in that part of the engagement which was unfinished.
I however, moved a little in it before I was quite recovered,
and was helped to get through the visit; though my weakness continued,
and many and deep were the attendant baptisms; but adorable kindness bore up,
and in some degree gave to drink, with a little living remnant,
of`' the brook by the way,`' and to praise the name of Him who lives forever.
While we were here, Esther Tuke came to Liverpool, though in a very infirm state,
feeling a desire to be at that meeting and a few others.
It was a little debt which she felt unpaid,
and she was desirous of finishing the day`'s work before the close came,
which seemed near.
She was favoured to finish the service which she had a prospect of,
and returned home peaceful, like a faithful and good servant,
and I believe was ready to receive the invitation--'`Come,
you blessed of my Father:`' and in a very short space of time she was gathered,
I doubt not, to an everlasting mansion of peace.

"`But the concern with which I left home was not yet accomplished,
so when I was a little recruited, being desirous not to lose time,
of which I think I cannot justly charge myself, being too apt to err on the other hand,
we left Liverpool for Manchester, and Sarah Benson, of Liverpool,
felt a concern to join us in a visit to the families of Friends there.

"`We attended the Monthly Meeting on a third-day,
and on fourth-day entered on the weighty service, for weighty it is,
as there is at seasons occasion to bring matters home, like Nathan did to David.
But the Ancient of days was near, and was pleased to renew a gracious visitation to many,
and in particular to the strayed sheep of the house of Israel,
that they might return to the Father`'s house in deep humiliation,
contrition and abasement, and then they would have bread enough and to spare.
In many of these opportunities, great brokenness was witnessed.
We found in this place, a precious exercised remnant, unto whom we were nearly united;
and at the close of the visit parted under the sweet
covering of that love which is the badge of discipleship.
We had one hundred and twelve sittings, besides the first-day and week-day meetings,
in twenty-eight days.
My poor frame was much worn down, but that felt of little consequence to me, though,
from the feeling of weakness, I was induced to question whether I might reach home.

"`From Manchester we went to Warrington, and attended their first-day meetings,
which were graciously owned by the Master, without whom the poor servants can do nothing.
We were also favoured in the evening with a precious opportunity at our lodgings,
many Friends being there.
The next day we went to Chester, and sat with a few in their families,
with whom we felt sympathy,
much desiring that the little that remains may be strengthened.
From Chester we went to Shrewsbury and had a meeting,
also went to see a Friend on his deathbed, which was a tendering opportunity.
He was soon after removed, I trust into that rest where sorrow is not known,
and all tears are wiped away, forever to unite in hallelujahs with the redeemed.

"`The same afternoon we went to Coalbrookdale;
and attended two meetings on a first-day to satisfaction.
In them, and in an opportunity in the evening,
consolation was administered to the mournful tried hidden ones.
Dear Ann Summerland was at both meetings, and also present in the evening.
How beautiful, to behold greenness in old age!
On second-day we went to Bewdley, and parted with dear Sarah Benson.
We had a meeting there the next day, and went afterwards to Worcester,
and from there home, taking only one meeting in our way.
I was favoured to reach Melksham the 6th of the twelfth month, 1794,
without any material accident; and though with a feeble body,
with a mind favoured with an evidence of having been moving in the humble,
and I trust faithful discharge of that duty, which was required of me by Him,
who is forever worthy to be served, worshipped and adored.`"

The following short extract of a letter written soon after her return from this journey,
may be a pleasant supplement.

[.embedded-content-document.letter]
--

It is matter of humble thankfulness, that, on looking back it affords peace,
and that I reverently feel a belief of having cleared the way;
not left undone what I ought to have done.
But notwithstanding, this language has been much the companion of my mind,
I am but an unprofitable servant.
Indeed I feel nothing whereof to boast, save infirmities,
and I hope a little in the cross of Christ.

--

In 1795, she was at London at the Yearly Meeting,
and in the following winter visited the families of Friends at Exeter, Shaftsbury,
Poole and Fordingbridge,
having a certificate addressed to Friends in the respective counties,
and in Somersetshire.
She returned early in 1796, with an acknowledgment of Divine help;
and in that year came again to the Yearly Meeting.
As winter approached she began to prepare for another journey, and obtained a certificate.
Her late companion, Mary Jefferys, jun.,
had also the Monthly Meeting`'s concurrence in bearing her company.
A prospect of visiting families was also before her in this journey;
and it may be remarked that though she had now been long accustomed to such visits,
and was a sort of veteran in the service,
it still appeared to her to be awful and arduous.

The following is very slightly varied from her own memorandums:

"`The 18th of the eleventh month, I left home, under no small weight of exercise,
having in prospect a visit to Friends in part of the eastern and southern counties,
also to the families of Friends at Norwich, and some other places: my dear cousin,
Mary Jefferys, Jr. being my companion.
We took Cirencester in our way, proceeding through Oxfordshire,
Buckinghamshire and Hertfordshire, into Suffolk and Norfolk,
going pretty direct to Norwich, and taking meetings as we passed along:
but the weight of the service of visiting families closely tried me.
We got to that city on seventh-day.
First-day we went to meeting, and near the close of it my way opened to some service,
and I was helped through to the ease of my own mind.
Next morning, by request,
the ministers and elders met together to give me
an opportunity of spreading before them my prospect.
I also gave them my certificate to read, and a solemn opportunity it was,
the precious wing of Divine love being measurably spread over us,
in which unity and sympathy were fully expressed,
and a willingness to afford any assistance in their power.
It was given with great readiness to the close of the visit;
and indeed we had a remarkably open door nearly through the whole;
but this was the Lord`'s doing, and marvellous in my eyes.
O, blessed be his holy name, who was mercifully near, renewing gracious help,
and opening fresh matter to the various states, from family to family,
under the precious tendering power of gathering love.
It was a time of renewed visitation to many.
O may the favours of heaven be rightly received and improved,
to the present and lasting advantage of their immortal spirits.
The baptisms through which my soul passed,
are only known to the full by Him who weighs the hills in a scale,
and the mountains in a balance; but the close was peaceful,
and the remembrance has caused humble thanksgiving.

"`We left Norwich the 23rd of the first month, 1797,
parting with some there in precious nearness.
The 24th, was at a meeting at Wymondham,
in which ability was given to labour closely and faithfully,
under that covering which covets to seek and save that none might be lost.
The 25th we rode to Swaffham, twenty-five miles,
and the next day had a meeting owned by Him who is
the light and life of his poor exercised children.

"`The 27th, we had a precious opportunity before we set off for Lynn.
In the way there, we called on a sick Friend with whom we had a tendering time.
Next day being seventh-day, we rested at Lynn; and on first-day,
after the second meeting, we entered on a family visit.
We had twenty-four sittings, including visits to those who attended our meetings,
though not in membership.
The opportunities with some of these sober people were to solid satisfaction.
We also visited the girls of a charity-school, and had a tendering time.
I think I never saw more general tenderness among children;
and their mistress was also affected.
I do believe the feet of the Lord`'s messengers will be
turned to look after children who are not of this fold.
What abundant labour and care has been bestowed on the children of our Society,
and how have some of them cast it behind their backs!

"`From Lynn we went to Wells, and were at a Monthly Meeting there,
a time of deep exercise, and sat with the few families.
Then we went to Holt, and on, by way of Norwich, to Yarmouth,
where also we visited the families of Friends.
We had thirty-seven sittings, in which gracious help was mercifully vouchsafed,
so that we were helped through the visit to the peace of our own minds,
and I humbly trust the seed was visited, the pure life a little strengthened,
and some afresh animated to press forward for the prize that is at the end of the race.
The lukewarm were warned of their danger,
and the rebellious invited to flee from the wrath to come.
The repeated close engagements, accompanied by daily baptisms,
with exposure to the cold air after being in warm rooms, much affected my feeble frame;
yet I did not feel myself at liberty to lie by to recruit,
but trusted in the holy Arm for help of body as well as of mind, so pressed forward,
and was mercifully supported.
When the visit was finished, we set off the following morning for Pakefield,
where we had a meeting in the evening, a humbling opportunity.

"`At this place, and in different places on the coast,
the people seemed under a fearful apprehension of an invasion by the French.
At many places, particularly Yarmouth,
there were a great number of military and naval men, whom it was affecting to see.
When will the desirable day approach, when the swords will be beaten into ploughshares,
and the spears into pruning-hooks, and the people learn war no more.
When I was on the Norfolk and Suffolk coast,
the feeling of a warlike spirit deeply affected my mind,
as being that to which the Lord Jesus came to put an end.

"`We had meetings at Beccles, Leystone and Woodbridge, and so on to Colchester,
where we visited the families and were mercifully helped;
but pressing on beyond my bodily strength, I was very ill when we got to Kelvedon,
and lay by some days.

"`We went from there to the Essex Quarterly Meeting, held at Coggeshall,
and returned to Kelvedon, attended the week-day meeting there,
after which rode on to Chelmsford,
and the next day to +++[+++the house of my relation William Storrs Fry, at]
Plashett; where I was poorly, but got to Barking meeting on first-day,
and to the Monthly Meeting there on third-day;
also to a public meeting held by desire of Sarah Harrison of Philadelphia,
which was a favoured season.
On fifth-day we attended a burial; and going the next day to London,
and resting there the day following, we were at Wandsworth meeting in Surry,
on first-day.

"`We left it in the afternoon for Esher, visited the families there,
had a meeting at Kingston, and another at Croydon,
and saw the Friends of two or three other meetings
in our way to the Quarterly Meeting of Surry,
held at Godalming, which we attended to satisfaction.
We were also at a burial at Guildford, and calling at Wanborough, near that town,
went from there home in two days, arriving at Melksham the 8th of the fourth month,
1797.`"
