== Chapter IX.

[.chapter-synopsis]
* Visit to America
* Letters
* Leaves home
* Embarks
* The voyage
* New York
* Family visit there
* Yellow fever
* Long Island
* Various services
* Quits New York
* Journey to Philadelphia
* Family visit in Pine Street meeting
* Laid up
* Goes to Germantown
* Soon returns to the city
* Confined to the chamber
* Visit of Mehetabel Jenkins
* State of mind, and expressions near the close
* Her decease
* Abstract of a testimony, etc.
* Conclusion.

We are now drawing towards the last travels of this indefatigable labourer.
We have seen the early arisings in her heart of Divine love.
We have remarked its increase,
and have had occasion to observe how she became willing to be the
instrument of conveying to others some portion of that bread,
on which she delighted to feed.
In pursuit of this object, and at the call of duty,
we have beheld her travelling in every district of these nations where Friends are settled.
In proportion to the interest which we have taken in the narration,
we may be said to have been the witnesses of her conflicts,
and almost to have partaken in her baptisms.
But neither her cup of suffering nor of consolation was by these completely filled.
A prospect of further service had been long opening on her view;
and when the right time for engaging in the labour appeared to have arrived,
she did not permit her feeble health, already impaired by past exercises,
to operate as an insurmountable discouragement.
She had often been strengthened by faith;
and she was prepared to follow her beloved Lord, either to life or death.

In the second month, 1801, in a very weighty manner, she laid before her Monthly Meeting,
her concern to visit Friends on the continent of North America:
her feelings on which occasion cannot, probably,
be better conveyed to the reader than by the following extract of a letter to her relation,
Joseph Storrs.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Melksham, 4th of Third month, 1801.

I have been confined to my chamber about a month, with a complaint, I believe,
much owing to deep exercise of mind;
and the first time of my getting to meeting was at our last Monthly Meeting,
though under great weakness of body, and heavy exercise of mind.
But, being reduced to obedience, I was enabled to lay before our Friends,
a prospect which had for many years attended my mind.
My dear cousin, it is nothing less than to go to America.
I have admired that such a poor creature should be called to service of such magnitude:
and so at times let in an apprehension that Friends would think me quite unfit; and then,
I should be excused on that ground.
But as the concern was spread before them, the meeting seemed dipped into great sympathy;
and, I believe, under Divine influence,
the language of encouragement was handed in a tender affecting manner.
So at home there seems no obstruction; and if at London there should be none,
and my health permit, it is likely we shall soon prepare to embark.
I say we, because my dear cousin Mary Jefferys felt herself so bound to the service,
that she believed she should forfeit her peace if she did not give up to it; of which,
in a solemn manner she informed Friends at the same time; which was, I believe,
very cordially united with.

You and my dear cousin Mary have tenderly felt with me under various exercises,
and I now claim it afresh in a particular manner;
with your prayers for preservation in every way: being indeed a poor creature,
but very desirous of being preserved from bringing any shade on the blessed Truth,
whatever becomes of this poor body.

[.signed-section-closing]
I remain your truly affectionate, exercised cousin,

[.signed-section-signature]
Sarah Stephenson.

--

To the foregoing, the succeeding extract of a letter to the same Friend,
is a suitable appendix.
It further demonstrates the tenour of her mind;
and leads through another step of the precaution enjoined by our discipline,
as a preliminary to travels on religious service in foreign parts.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Melksham, 11th of Fourth month, 1801.

Your tender sympathy under the baptizing power of Truth,
has bowed my spirit under a sense of my unworthiness;
and raised thankfulness for the near unity of my dear friends, in this awful prospect.
May every future step of my life (a poor worm,) be ordered in the pure
fear of Him who has a right to make use of the weak of this world,
that so the continuation of this precious unity may be mercifully granted,
to the close of my days, whether they be many or few.
For, oh! the unity of the brethren is to me exceedingly precious;
and even with this blessing, under the many conflicts and sore baptisms,
in the course of my little experience in journeys, my faith has often been tried,
as to a hair`'s breadth; and I do not expect an easier path;
but how must it be without the unity and sympathy of Zion`'s faithful travellers?

Our Quarterly Meeting was held here last week, when, to my humbling admiration,
a current spread of tender sympathy, and as Friends expressed, of unity.

[.signed-section-closing]
I remain, etc.

[.signed-section-signature]
Sarah Stephenson.

--

After this our friend attended the Yearly Meeting.
In the meeting of ministers and elders,
she opened her view of visiting the American continent with much weightiness of spirit,
and obtained its concurrence and a certificate.
Her services in the sittings of the women`'s meeting,
and the humility which appeared to clothe her mind, are said to have been very edifying.
She promoted and assisted in the writing of an epistle from that meeting, thus,
as she expressed it,
relieving herself of a little debt which she seemed to owe to her sisters in this land,
before she left them, and as it proved, finally.

Having now obtained the full concurrence of all the meetings which
are appointed to watch over concerns of a nature so important,
she returned home to Melksham, which town or its neighbourhood had been her residence,
when she could be said to have a home, for nearly thirty years.
But she soon left it again, and went to Bristol, her port of embarkation,
in the latter part of the sixth month, accompanied by her justly dear friend,
relation and companion, Mary Jefferys, jun.,
who was also furnished with certificates of the full unity of Friends.
About an hour before she went from home, being in her chamber,
having only with her one of the sisters of her companion,
who was much affected with the probability of a long separation, she said to her,
"`I feel nothing more to do here.
If I stayed with you,
I should be no comfort to you:`" and observed that the crown was at the end of the race.

Let us now attend to her own narration, which she has left nearly in the following words:

"`The 8th of the seventh month, 1801, we went on board the ship Uncle Toby, Elihu Doty,
captain, lying at Pill, near Bristol.
We stayed two nights, but the wind being contrary,
we came on shore the 10th to a Friend`'s house about two miles distant,
where we also stayed two nights, and then were called up early,
the wind being tolerably fair, though the weather was unsettled.
The captain being very anxious to get out, set sail;
but in a few hours we had a head wind and a very rough sea,
so that I apprehend we were in considerable danger.
On seventh-day night I was very ill, not able to undress, but got into my berth.
On first-day morning the pilot thought it best to run back from the Holmes to King-road,
which we reached by noon, and then anchored.
About three o`'clock, I was helped out of my berth, and about five,
we had a meeting in the cabin.
The captain, his wife and sisters,
also the pilot and some of the steerage passengers sat with us.
It was a season that I trust was owned by Him whose ways are ways of wonder.

"`On second-day, the 13th, in the afternoon, we went on shore again,
but it was with difficulty that I got to our kind friend`'s house,
feeling much bodily weakness; but there I was tenderly nursed.
The stormy weather had occasioned our friends at Bristol to be very uneasy about us.
On their being informed that we were on shore,
my dear sister with several others of our affectionate friends soon came to see us;
and I believe, with us were reverently thankful to the great Preserver of men.
It was a favourable circumstance to me that the wind continued unfair for several days,
for in that time I recruited considerably; and on sixth-day, the 17th, we went on board,
and sailed about eleven o`'clock in the morning;
passing several vessels of different descriptions.
The 18th, towards evening, we cast anchor in sight of Ilfracombe, Devonshire,
and lay by a few hours waiting for the tide.
The next day being come to Lundy island, the pilot left us early in the morning;
and this day we lost sight of English ground.
On the 23rd having had a brisk wind since the 19th, and part of the time pretty much aft,
we had got forward upwards of six-hundred miles.
The next day the wind was right ahead; and the 25th a brisk gale,
with lightning and a pretty heavy storm in the morning.
In the afternoon a vessel hailed ours by a gun, and soon made up to us, put out the boat,
and sent an officer on board to examine the captain.
But he soon returned as we were not a prize for this ship, which was a ship of the line,
called the St. Alban`'s from Nova Scotia, bound for Plymouth or Portsmouth,
and convoying two ships laden with masts.

"`1st of the eighth month.
For several days many of the passengers have been very sick,
in part from the great motion of the vessel, particularly one night,
which was almost tempestuous.
The 10th we got nearly, or quite to the grand banks of Newfoundland;
and the next day a boat from our vessel went to a fishing schooner that lay pretty near,
from which we had a plentiful supply of cod-fish;
and besides these our men caught many large ones.
The 12th the sailors saw a log floating which they took in tow.
A great number of small fish soon followed it, some of which were taken,
and proved very good.
The log was nearly covered with barnacles, which I believe, attracted the small fish.
The 13th, we were in fifty-four fathoms water,
and the 14th got off the banks of Newfoundland, the weather being much warmer.
On first-day, the 23rd, the wind was quite ahead.
After we were gone to bed, the mate called up the captain, apprehending danger.
It proved to be a sea-race.
There was also thunder, lightning and heavy rain for some time,
so that we had a disturbed night.
The next day the wind continued ahead, and we came to soundings in sixty fathoms water,
near George`'s bank.

"`On the 25th, a fine morning and a fair wind, and we went seven knots an hour.
In the afternoon the wind was rough, and there was a swell of the sea,
so that it was with difficulty we could keep our seats;
but it became stiller by bed-time.

"`The 27th of the eighth month; we shall have been on board six weeks tomorrow,
and I apprehend we are now about two hundred miles from New York.
The passage thus far has on the whole been favourable,
though not without storms of thunder, lightning and rain, with high and squally winds,
but not of long continuance.
Indeed the language may justly be adopted, '`Great and marvellous are your works,
Lord God Almighty.
Just and true are your ways,
O King of saints.`' To relate all I have passed through from various causes,
would take much time and paper, and I do not feel much inclination to attempt it.
Let it lie buried in the deep recesses of my heart until called for,
for the benefit of poor tried travellers, or to have recourse to, for my own instruction,
benefit and encouragement.
And may I be qualified to say,
'`I know that my Redeemer lives,`' being thereby enabled
to drink the future bitter cups that may be assigned,
with increasing submission and willingness;
that so the reward of the willing servant may be mercifully granted to me,
one of the weaklings of the flock.
When I have been led to look back, and to remember the unity and sympathy,
which my dear friends expressed, it has caused me greatly to admire,
and being permitted to feel something of a sweetly cementing fellowship of spirit,
since enclosed in this floating house, may I be so preserved, and enabled so to move,
that my spirit may be permitted to unite with the
Lord`'s humble tribulated faithful servants,
in the land to which I am bound;
that no reflection may be cast on those who have certified for me,
nor on those who publicly or privately expressed their unity and tender sympathy;
but above all, that the blessed cause may have no shade brought on it through me.

"`About five o`'clock in the afternoon, the 28th, the captain espied land,
which proved to be Long Island.
It was seen pretty clearly; but the wind being quite ahead, we could not get forward:
a light squall in the evening.
On the 30th, the wind was fair, but we lost sight of land for awhile.
In the evening a pilot came on board, and informed us that New York is healthy.
We lay at anchor that night, and next day moved early in the morning, the weather rough,
with thunder, lightning and rain.
In the afternoon, we were favoured to land safely,
and were kindly received at Robert Bowne`'s, who came with a boat,
and conducted us from the vessel to his house.
My mind with my dear companions^
footnote:[Besides her companion, Mary Jefferys, there went in the same ship Samuel Smith,
of Philadelphia, a ministering Friend,
returning from a religious visit to Friends in Ireland and some parts of England.]
were, I believe, deeply humbled with acknowledgements to the God of all grace,
for the favour of being brought safely to land.

"`On our arrival at New York, or a day or two afterwards,
the weather became extremely hot, which, with the mosquitoes,
after being much exhausted with sickness at sea and confinement on ship-board,
was very trying: so that a little rest in the country was highly needful,
and proved salutary.
After this we went on the Main,
and visited five meetings then passing again through New York to Long Island,
we visited meetings there.
After this we returned to the city,
and I laid before the members of the meeting of ministers and elders,
a concern to visit the families; with which they concurred.
The yellow fever having broken out, it was an engagement increasingly solemn,
yet feeling it right to begin, and many of the members being in the country,
we visited several of those families,
as it was not thought prudent for us to be much in the city;
and I trust and believe it was in the right time;
a season when the rod seemed to be awfully held over the city;
and when the gracious gathering arm of Omnipotence was extended,
for the help of those who were willing to be gathered.

"`The Quarterly Meeting to be held on Long Island coming on,
it seemed right to attend it; so we crossed the East river at a ferry called Hurlgate,
and rode to Flushing where it was held;
the meeting of ministers and elders on the 21st of the tenth month,
was a season of deep exercise, but owned by the Master.
That day I was sixty-three years of age.
On the 22nd, the men and women sat together for about an hour,
during which a good degree of solemnity was felt to spread; then separating,
each part went to its business.
It was a time of deep exercise to me.
I was led into very close, but affectionate labour;
and I humbly hope the meeting ended to satisfaction.
On the 23rd was a large public meeting, in which my spirit was deeply baptized,
and after sitting about one hour in silence, which to me was solemn and awful,
I felt it my place to stand up, to deliver matter as it might open,
much of which was very close and searching;
but a stream of comfort and encouragement flowed to the exercised travailers,
and of this description there are on this island,
unto whom my deeply exercised soul was united.
On the 25th we went to Westbury, and after meeting there, the next day to Newtown.
The 27th, we again crossed the ferry and went to Mamaroneck, about twenty-three miles,
and next day to the meeting of ministers and elders at Purchase,
which was a low exercising time.
On the day following was the meeting for business,
and while the men and women sat together, I was closely engaged:
but gracious help was afforded, under the covering of love, to deal plainly.
There was also a public meeting, in which I was largely exercised.
I humbly trust, life was felt in a good degree over the meeting.
In the afternoon we rode to Mamaroneck, and the 30th to Harlem.

"`Though deep baptisms and close exercise have been my daily portion,
yet I have cause for reverent thankfulness, in having been mercifully helped thus far;
and I humbly hope the cause of Truth has not suffered by me.`"

Here ended her memorandums; but in a letter, dated near Rahway,
the 28th and 30th of the first month, 1802,
she mentions the accomplishment of the family visit at New York, nearly as follows:

[.embedded-content-document.letter]
--

Though my mind was often low, yet merciful Goodness was underneath,
so that through the renewing of daily help,
that arduous service at New York was finished under the feeling of peaceful serenity.
We had about two hundred and eighty sittings, besides attending meetings,
and other opportunities of religious service: I was much spent,
and my poor shattered frame needed to be recruited by a little rest.
But New York did not seem the place for it,
though the kind Friends at whose house we lodged, manifested, if it could be,
increasing sympathy and love.
Feeling easy to leave the city, my desire was strong to be moving forward,
and as the roads at that time were bad, we went, on the 23rd of the first month,
on board a small vessel, to Elizabeth Town Point, in Jersey.
After taking refreshment there, we went in a wagon provided for us to Rahway;
and the next day, being first-day, attended the two meetings there.
Second-day forenoon was spent in visiting a school and some families.
In the afternoon we came here, and I was taken so unwell, that I could hold up no longer,
but soon got to bed, my head being in violent pain, with great oppression on my chest,
attended with spasms.
After being prevailed on to take some medicine,
I was somewhat relieved of the pain in my head;
and if I continue mending I hope we may set off in a few days for Philadelphia,
without taking many meetings by the way, as the roads are yet very bad.

--

The 31st, being better, though yet very weak, she proceeded accordingly,
attending by the way, the meetings of Plainfield, Stonybrook, Trenton and Bristol,
in all of which she was strengthened to labour,
under the influence of that pure love which seasoned
her communications and evidently made way for them,
to the edification or comfort of others, and to the peace of her mind.
The 8th of the second month, she went to Frankford, where, being more unwell,
and having a rash out, and the weather being cold,
she did not attend the week-day meeting;
but in the afternoon being met by her dear friend Sarah Harrison,
whom she had known in England, when on a religious visit there,
and by some other Friends from Philadelphia,
she was desirous of returning with them the same evening as the distance was easy.

After arriving at Thomas Harrison`'s, where she met with a very cordial reception,
several Friends of the city called to speak to her.
To one who asked her how she did, she replied, "`She was but poorly;`" and added,
rather in a pleasant manner, "`Will you give me about six feet of ground?
I don`'t know but I am come to lay down my poor body among you.`"
Sarah Harrison, as well as others, was affectionately desirous of her taking rest,
which appeared needful; but after being nursed for a few days, she went to meeting,
and for several weeks attended the meetings in the city generally,
as they came in course.
The three Monthly Meetings there happened about that time,
in which she produced her certificates, and had some tendering opportunities, which,
as she afterwards remarked, were relieving to her mind.^
footnote:[About this time twelve or more Indians, coming to Philadelphia on business,
had a conference with Friends; to whom they applied for help or information.
At this conference Sarah Stephenson was present,
and was engaged to address them in a feeling suitable manner.
Her address being interpreted to them, they expressed in their way,
much satisfaction and approbation.
They were told by Nicholas Wain, from which she came,
and on what account she had crossed the mighty waters.
At parting, they appeared grave and solid, and were earnest to shake hands with her.]
But she still continued languid;
yet she imparted to Friends a view which she had of visiting
the families belonging to Pine Street meeting.
This was acceptable information, and cordially received;
but a desire was expressed by some,
that there might not be a pressing forward beyond her strength.
The engagement was accordingly entered upon the 9th of the third month;
but her weakness was such,
that three visits in the day were more than she was equal to without being much fatigued.
She was therefore again obliged to submit to lie by to be nursed; but she said,
that "`making of the attempt had afforded her satisfaction,
whether she lived to move further in it or not.`"

After awhile, as her strength did not increase, nor her complaints lessen,
she was advised to go into the country for change of air;
so she went to the house of a kind Friend at Germantown,
where she continued nearly two weeks and once attended the meeting;
but for the most part kept her room.
She thought the air salutary at first; but not finding any material benefit,
she returned to the city,
and went to the house of a Friend within the district
where she had begun her family visit:
her increased weakness was apparent by her not bearing the ride back,
which was about seven miles, without much more fatigue than she experienced in going.
She went soon to her chamber, and after the 4th of the fourth month, which was first-day,
she came down stairs but once.
On that day, she was desirous of attending Pine Street meeting, which she did;
but was then in so weak a state that her being there was matter of surprise to some.
To a Friend who was discouraging the attempt,
fearing the fatigue would be too much for her, she said with great emphasis,
"`I love to go to meeting!
I love to go to meeting:`"^
footnote:[This is a signal and encouraging testimony, from the mouth of one,
whose frequent allotment in meetings had been deep travail, exercise and baptism.]
and she remarked that "`she had sometimes surprised her friends
at home by going from her chamber to meeting when very poorly,
and that at times she thought she felt less pain
and weakness of body there than at home;`" and added,
"`that those who used their utmost endeavours thus to meet with their friends, would,
she believed, have satisfaction in looking back on it, when deprived of that privilege.`"

From this day, she was wholly confined to her room, and the 9th she took to her bed,
only leaving it in order to have it made, for several days.
Afterwards she seemed rather better again,
and sat up a considerable time in the middle of the day;
but she generally had very disturbed nights,
being troubled with cough and a restlessness from fever.
She could bear but little company,
stillness affording her complaints more alleviation than
the kindness of Friends in any other way could afford;
and therefore she saw but few.
But Mehetabel Jenkins, who, as has been related, had known her in England,
being in the city on religious service, and desirous to see her,
paid her an acceptable visit.

On the 12th, sitting by her bedside, after a time of silence, she sweetly addressed her,
in testimony of her belief that the present dispensation was of the Lord,
who does all for the best;
though his workings were sometimes in a way past our finding out, yet always right;
and that whatever might be the termination of her bodily indisposition,
she believed all would be well with her, and that there was nothing in her way;
but that He whom she had long loved,
and faithfully followed would be with her to the end;
that she felt great sweetness in sitting by her,
and had an apprehension that she was near being gathered to the sabbath of rest.
With more in a comfortable way, bidding her dearly farewell.
At that time, Sarah said very little; but a few days after, referring to the visit,
she said, "`Dear Mehetabel, if her view should be verified,
it would be a great favour to me.
I was very low in body, and so weak at that time,
that it seemed as though I could hardly lift up my hand or move.
I did not choose to say so then;
but it did feel to me that there was nothing in the way.`"
She also added, "`It affords me no pleasure,
when anyone speaks of my recovery being likely; for through merciful kindness,
I humbly hope all would be well if I was taken now; and if I stay longer,
it might not be better: so that none should desire my continuance in this state of being,
subject to conflict and trials, of which I have so long endured a share;
and even since being in this city deep have been my baptisms,
only fully known to my own soul,
and to Him who knows for what cause they are my portion.`"

The 19th and 20th, she appeared rather better, and sat up part of each day.
She said she understood the doctor thought her better,
but that she did not feel herself so.
She inquired whether any thought she indulged too much, by thus lying by to be nursed,
and frequently acknowledged "`what a favour it was that her allotment
at this time was with such as were not only freely disposed,
but of ability, to render every comfortable accommodation,
which her situation required.`"

Early in the morning on the 21st,
she said she had been thinking much in the night of a young man,
for whom she had been religiously concerned; and she desired to have something written,
which she wished to be conveyed to him; but in general since her confinement,
exercise of mind on account of others, seemed mostly taken from her; having,
as she observed, done what she could when in better health,
and now wished others might feel for themselves.

The 22nd, a Friend proposing to read a letter from one she knew and loved;
she asked whether it was interesting.
A part of it was read; but as she appeared indifferent, the Friend left off,
lest it should fatigue her.
On this, she said, "`I seem to be got past these things;`" and added after a pause,
"`by saying so, I mean I do not wish to have my attention drawn out.`"
The same day, in a clear and weighty manner,
she commissioned a Friend with a salutation she felt to Friends in her native land.

The 23rd, about five o`'clock in the morning, she was seized with a hard cough,
which continued, without much respite for nearly or quite an hour,
with a great discharge of heavy phlegm, so that she seemed almost exhausted,
and it left symptoms which encouraged her hope that
her release from the conflicts of time was near.
About the middle of the day she gave some directions
respecting the disposal of her clothes;
naming some who had come under her notice,
to whom she thought little legacies might be acceptable and useful;
her tender feeling for those in straitened circumstances, which was great,
continuing to the last.
Her companion being much affected with sorrow, Sarah took her by the hand,
and affectionately entreated her not to give way to it; saying,
"`She did not know how it might be.
She might yet recover; but it would be unkind to covet her continuance, for while here,
she expected to be a cripple, the weakness of her limbs was so great,
particularly her right side.`"
She also remarked,
what a favour it was to her companion to be left among so many friends,
who would extend their tender care,
and that she believed she would be supported and rewarded;
desiring that "`she would not grieve for her,
since if consistent with the will of her good Master,
it would be far better for her to be removed then;
and that she had never expected or desired to cross the water again.`"
One day the doctor proposing something to strengthen her stomach, she said to him,
with a smile on her countenance, "`Doctor, I did not want you to strengthen me.
When I look towards going, it feels so pleasant, that it seems like a trial to return.`"

The 24th, she said to one who was affected by observing her increasing weakness,
"`Don`'t be at all uneasy, I have been sweetly comforted by my good Master`'s presence.`"
To a Friend who remarked that her "`bed had been made in sickness;`" "`Yes,`" said she,
"`wonderfully so.`"
Being then asked how she felt respecting her recovery, she replied,
"`I have no prospect of it.
I believe I have finished the work.
There is nothing in the way.
I have no care, but on account of my dear child.`"
By this term she meant her companion, and addressing her, she added, "`But, my dear,
you had nothing else to expect when we left home.`"
Something being proposed for her to take, she said,
"`My friends propose things which I sometimes comply with;
but it seems precious to look towards a release.`"

Her companion having told her that she felt quite satisfied in having come,
and that she thought it a favour to be with her at that time, even if,
by means of Sarah`'s removal,
she should be left thus far from her native land and her friends there,
Sarah seemed almost overcome with joy; and said, '`Now how glad I am, how glad I am,
that you hast told me this.
It is enough, Oh,
it is a great comfort to me.. Now I hope my good Master will soon take me to rest;
and you wilt be supported and rewarded.
There is little here but trials, disappointments and conflicts.
Now don`'t hold me, my dear.`"
Then she seemed as if she would soon sink away; but was heard to say, in a low,
but melodious voice, "`Glory, glory.`"
Soon after a Friend and his wife came in, whom she much loved; and she said,
"`Dear Thomas, may the blessing rest upon you.
May the blessing of the Lord rest upon you and your house,
as it did on the house of Obededom, where the ark of the covenant rested.
Farewell, dear Thomas, farewell.`"

One day a Friend asked her how she felt; to whom she replied,
"`I have been remarkably quiet for some days past; I am sometimes afraid too much so.`"
The Friend returned, The great Master declared,
"`In my Father`'s house are many mansions;`" and expressed her belief that if
Sarah had not been prepared to enter into one of these glorious mansions,
he would have made her sensible of it,
and would not permit her to lie in that quiet easy state of mind.
With this remark Sarah seemed satisfied.
Her strength was much decayed; and on the 26th of the fourth month, which was second-day,
her breathing was become difficult and painful, and she felt great oppression of body.
"`This,`" said she, "`is wearing work:`" but nevertheless she lay very still,
as she had been enabled to do during the whole of her illness;
and several times desired not to be disturbed.
After a hard fit of coughing, with a discharge of phlegm, which left her much spent,
she said, "`It will be right, let it be which way it may;
and that is better than all the world.
It seems as if it must be nearly over now: I have so little strength left.`"
A little after, she seemed to be uttering praises, saying, "`How good,
how good!`" and appeared like one engaged in sweet supplication.
A Friend asking her how she did, after a pause she replied, "`I cannot say much:
but my King reigns.`"
Afterwards, at three different times, being very weak and her voice low,
she was understood to say, "`deathbed;--I am passing away;--Lord take me.`"

Asking what o`'clock it was, and being told about one, she said, "`Time passes slowly.`"
Feeling increased difficulty of breathing,
pain in her stomach and great oppression at her chest, she said,
"`Give patience:`" with which, that she was largely endued,
those around her could witness.
Again she asked the time of the day, and said, "`I love quietness,
don`'t let me be disturbed.`"
Soon after, finding herself sinking fast,
she seemed desirous of taking her last leave of those around her,
and saluting them with her dying lips, said, "`Farewell, farewell.`"

Previously to her departure, her conflict of body had some time subsided;
and a few minutes before seven o`'clock in the evening,
in the sixty-fourth year of her age, quietly and sweetly she ceased to breathe.
Here, reader, pause, Dwell on the closing scene,
and taste the blessedness of the death of those who die in the Lord!
