[#testimony1, short="Testimony of Wiltshire Meeting"]
== An Abstract of the Testimony of the Monthly Meeting of Wiltshire.

Our much beloved friend Sarah Stephenson,
a member of this meeting for upwards of thirty years,
having been one whose example preached sweet instruction,
we desire the remembrance of it may have the same influence,
and be a further incitement to follow her, as she followed Christ.

She was entrusted with a gift in the ministry about the twenty-eighth year of her age.
In the exercise of this weighty calling she was often engaged,
under the persuasive influence of Gospel love to labour with the youth,
for whose preservation in true simplicity, she felt strong and affectionate solicitude:
that they might dedicate all to Him who loves an early sacrifice,
of which she was a great example.
Her ministry was sound, tending much to raise into dominion the hidden life.
Her path was often in the deep; and by such baptisms,
she was enabled to minister to the states of the
people in the power and efficacy of the Gospel.
Leaning on the arm of All-sufficiency, she was made an eminently useful instrument.

To adopt the expressions of a testimony we have received from New York, we can say,
"`She was peculiarly qualified to move with propriety
in that great work of going from house to house:
a meek and quiet deportment, a mind clothed with a spirit of love,
and affectionate solicitude that all might be gathered within the Divine enclosure,
being conspicuous traits in the character and conduct of our beloved friend.`"

With the afflicted, whether in body or mind, who came under her notice,
she was a true sympathizer.
She frequently said she wished not to outlive this tender sensibility;
and she manifested it to the last.
Near her close, she said she had great satisfaction as she passed along,
in having imparted of her little to those that had less.

In the sixty-third year of her age,
she opened to Friends a prospect which she had long kept secret,
of paying a religious visit to Friends in America.
This undertaking seemed arduous;
more especially as her natural strength at that time had much declined;
but as she observed, it seemed of no consequence to her where her life might close,
so that when the solemn period came, she was but where and what she ought to be.

She was much satisfied with having come to that land, which appears by a message which,
a few days before her close,
she seemed desirous to be conveyed to Friends in her native land,
and commissioned a Friend with the following:
"`I feel a salutation of Gospel love flow towards them;
and have thankfully to acknowledge that I have met
with those among faithful Friends here,
who have felt as fathers and mothers, brethren and sisters;
that I find the Lord`'s tenderly concerned baptized travailing children,
to be the same everywhere; and though from my present weak state,
it is rather unlikely I shall ever see them again in mutability,
I am perfectly satisfied with being with Friends in this land,
and quite easy as to the outcome of this my present indisposition;
desiring the Lord`'s will may be done.`"

During her illness she said that, though it was desirable to her to go,
yet if it were the Divine will that she should again be raised up,
and introduced to her arduous line of service, she had felt sweet submission to it.
But her work was mercifully cut short in righteousness;
and the sacrifice of a willing mind accepted by Him
who thus manifested his love unto the end.

She breathed her last the 26th of the fourth month, 1802, aged sixty-three years,
a minister about thirty-six years.
Her remains were interred in Friends`' burial-ground in Philadelphia,
the 29th of the fourth month.
As there is cause to believe she answered to the description in the inquiry,
"`Who is that faithful and good servant,
whom the Lord shall make ruler over his household,
to give them their portion of bread in due season;`" we have +++[+++also]
the consoling belief that the annexed blessing was her reward; "`Blessed, I say unto you,
is that servant, whom his Lord, when he comes, shall find so doing.`"

Signed in and on behalf of the aforesaid meeting held at Melksham,
the 14th of the twelfth month, 1802.

The following is an extract of a letter to a Friend in England, written by the deceased,
from the city of New York.

[.embedded-content-document.letter]
--

Although, my dear, we are very far outwardly separated,
this is not able to prevent sweet union of spirit,
and humble intercession for strength to advance towards the holy city,
where the saints`' solemnities are kept.
O, the joy that will there be revealed, and forever remain, without alloy!
That our poor feeble spirits may be daily engaged in this humble fervent travail,
is the desire of my soul: that so, through adorable mercy, we may be favoured to meet,
never to part; and with the just of all generations,
unite in the glorious song of Moses and the Lamb!

--
